import {createFlowerChoices,expandFlowerPlan} from './flower-plans.js';
import {flowerStage,isLearned,packCardCounts} from './learning-progress.js';
const W=1672,H=941, canvas=document.querySelector('#garden'),ctx=canvas.getContext('2d');
const img=new Map(), hit=[]; let catalogue, screen='home', message='', held=null, editorMode=null, inventoryOffset=0, gameOffset=0, shopOffset=0, shopTierOffsets={}, pointer={x:W/2,y:H/2}, confirmation=null, activeGameSession=null;
const GARDEN_POINT_REWARDS={normal_round_completed:10,training_round_completed:5,pack_completed:100};
const names=s=>s.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase()).replace(/^Ui\b/,'UI');
const missingFlowers=new Set();
const load=src=>new Promise((ok,bad)=>{const i=new Image();i.onload=()=>{img.set(src,i);ok(i)};i.onerror=bad;i.src=src});
const fresh=()=>({save_version:1,settings:{selected_pack_scope:'all_active',minigame_sort:'recent',last_inventory_filter:'plants',last_focused_row:'row_1',background:'assets/backgrounds/field.png',horizon:.5,row_count:6,max_new_introductions:3,round_size:10},rewards:{garden_points:0,lifetime_garden_points:0,highest_unlocked_tier:1,tier_purchase_counts:{},completed_packs:[]},pack_progress:{},garden:{rows:[{id:'row_1',created_at:new Date().toISOString()}],focused_row:'row_1'},inventory:{furniture:[],decorative_plants:[]},game_usage:{}});
let save=fresh(), activeUserId=null, userList=[];

function button(x,y,w,h,label,fn,opts={}){ctx.save();ctx.fillStyle=opts.active?'#496b43e8':'#fff9e5e8';ctx.strokeStyle='#5c6d43';ctx.lineWidth=3;round(x,y,w,h,14);ctx.fill();ctx.stroke();ctx.fillStyle=opts.active?'#fffbe6':'#35442e';ctx.font=`${opts.size||22}px Georgia`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(label,x+w/2,y+h/2);ctx.restore();hit.push({x,y,w,h,fn});}
function debugButton(x,label,hours){ctx.save();ctx.fillStyle='#b91f1f';ctx.strokeStyle='#fff4e5';ctx.lineWidth=3;ctx.fillRect(x,50,52,52);ctx.strokeRect(x,50,52,52);ctx.fillStyle='#fff';ctx.font='bold 24px Arial, sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(label,x+26,76);ctx.restore();hit.push({x,y:50,w:52,h:52,fn:()=>advanceTime(hours)});}
function imageButton(src,x,y,w,h,fn,label=''){const i=img.get(src);if(i)ctx.drawImage(i,x,y,w,h);if(label){ctx.fillStyle='#fff4cf';ctx.font='bold 25px Georgia';ctx.textAlign='center';ctx.fillText(label,x+w/2,y+h/2+8)}hit.push({x,y,w,h,fn});}
function round(x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r)}
function activeBackground(){return save.settings.background||'assets/backgrounds/field.png'}
function background(){let image=img.get(activeBackground())||img.get('assets/backgrounds/field.png');ctx.drawImage(image,0,0,W,H)}
function allItems(){return Object.values(save.pack_progress).flatMap(p=>p.items||[])}
function planted(){return allItems().filter(i=>i.plant.status==='planted')}
function stage(item){return flowerStage(item)}
function moisture(item){return Date.now()>=Date.parse(item.next_review_at)?1:0}
function wateringCount(items){return items.filter(item=>moisture(item)===1).length}
function drawWateringStatus(){let active=wateringCount(selectedItems()),total=wateringCount(allItems());ctx.save();ctx.fillStyle='#fff9e5e8';ctx.strokeStyle='#5c6d43';ctx.lineWidth=3;round(220,25,280,78,16);ctx.fill();ctx.stroke();ctx.fillStyle='#35442e';ctx.textAlign='left';ctx.textBaseline='middle';ctx.font='bold 20px Georgia';ctx.fillText(`Active pack: ${active}`,250,48);ctx.font='18px Georgia';ctx.fillText(`Total: ${total} need watering`,250,79);ctx.fillStyle='#4c8fb3';ctx.font='bold 25px Arial, sans-serif';ctx.textAlign='center';ctx.fillText('💧',235,63);ctx.restore()}
function rowProjection(depth,rowShift=0){let count=save.settings.row_count||6,horizon=(save.settings.horizon??.5)*H,distance=rowShift+Math.max(0,Math.min(1,depth)),t=Math.min(1,distance*2/count);return {y:H+(horizon-H)*t,scale:.94*(1-.75*t)}}
function flowerSheet(type){let path=`assets/flowers/${type}.png`,sheet=img.get(path);if(!sheet){if(!missingFlowers.has(type)){missingFlowers.add(type);console.error(`Missing flower sprite: ${path}. Saved assignment preserved; showing fallback.`)}sheet=img.get(catalogue.flowers[0]?.image)}return sheet}
function flower(item,rowShift=0,alpha=1,finalStage=false,xOverride=null,yOverride=null){const sheet=flowerSheet(item.plant.plant_type);if(!sheet)return;let d=Math.max(0,Math.min(1,item.plant.depth??0)),projection=rowProjection(d,rowShift),scale=(item.plant.scale||1)*projection.scale;let sw=sheet.width/4,sh=sheet.height/2,x=xOverride??item.plant.x*W,y=yOverride??projection.y;ctx.save();ctx.globalAlpha=alpha;ctx.drawImage(sheet,(finalStage?3:stage(item))*sw,moisture(item)*sh,sw,sh,x-sw*scale/2,y-sh*scale,sw*scale,sh*scale);ctx.restore()}
function furnitureGeometry(f,rowShift=0,xOverride=null,yOverride=null){let d=Math.max(0,Math.min(1,f.depth??0)),projection=rowProjection(d,rowShift),scale=(f.scale||1)*projection.scale,im=img.get(f.image),x=xOverride??f.x*W,y=yOverride??projection.y;return {im,x,y,scale,w:im.width*scale,h:im.height*scale}}
function drawFurniture(f,rowShift=0,alpha=1,xOverride=null,yOverride=null){let g=furnitureGeometry(f,rowShift,xOverride,yOverride);ctx.save();ctx.globalAlpha=alpha;ctx.drawImage(g.im,g.x-g.w/2,g.y-g.h,g.w,g.h);ctx.restore()}
function rowItems(row){return [...planted().filter(i=>i.plant.row_id===row),...save.inventory.furniture.filter(f=>f.status==='placed'&&f.row_id===row)]}
function newestOccupiedRow(){return [...save.garden.rows].reverse().find(r=>rowItems(r.id).length)?.id||save.garden.rows.at(-1).id}
function activeArea(){return {left:W*.02,right:W*.98,top:rowProjection(1).y,bottom:H}}
function drawActiveArea(){let area=activeArea();ctx.save();ctx.fillStyle='#42a84633';ctx.strokeStyle='#287c3c99';ctx.lineWidth=3;ctx.fillRect(area.left,area.top,area.right-area.left,area.bottom-area.top);ctx.strokeRect(area.left,area.top,area.right-area.left,area.bottom-area.top);ctx.restore()}
function drawObjects(focusedRow=save.garden.focused_row,highlightActive=false){const focus=save.garden.rows.findIndex(r=>r.id===focusedRow),limit=(save.settings.row_count||6)+2,visible=save.garden.rows.slice(0,focus+1),behind=[],active=[];for(let ri=0;ri<visible.length;ri++){let id=visible[ri].id,shift=focus-ri;if(shift>limit)continue;let target=shift?behind:active,darken=draw=>()=>{ctx.save();ctx.filter='brightness(50%)';draw();ctx.restore()},effect=highlightActive&&shift?darken:draw=>draw;for(const it of planted().filter(i=>i.plant.row_id===id&&i!==held))target.push({depth:it.plant.depth+shift,draw:effect(()=>flower(it,shift))});for(const f of save.inventory.furniture.filter(f=>f.status==='placed'&&f.row_id===id&&f!==held))target.push({depth:f.depth+shift,draw:effect(()=>drawFurniture(f,shift))})}behind.sort((a,b)=>b.depth-a.depth).forEach(o=>o.draw());if(highlightActive)drawActiveArea();active.sort((a,b)=>b.depth-a.depth).forEach(o=>o.draw())}
function home(){background();drawObjects(newestOccupiedRow());imageButton('assets/ui/new_pack_button.png',35,26,165,118,()=>screen='packs');
 let scopes=['All Active',...Object.entries(save.pack_progress).filter(([,p])=>p.status==='active').map(([id])=>names(id)),'All Everything'];let current=save.settings.selected_pack_scope==='all_active'?'All Active':save.settings.selected_pack_scope==='all_everything'?'All Everything':names(save.settings.selected_pack_scope);let cycle=d=>{let n=(scopes.indexOf(current)+d+scopes.length)%scopes.length;save.settings.selected_pack_scope=scopes[n]==='All Active'?'all_active':scopes[n]==='All Everything'?'all_everything':Object.keys(save.pack_progress).find(k=>names(k)===scopes[n]);persist()};
 drawWateringStatus();
 imageButton('assets/ui/pack_left.png',520,25,65,78,()=>cycle(-1));imageButton('assets/ui/pack_title_frame.png',590,18,360,96,()=>{},current);imageButton('assets/ui/pack_right.png',955,25,65,78,()=>cycle(1));
 if(save.settings.debug_mode){debugButton(1316,'1',1);debugButton(1378,'6',6);debugButton(1440,'24',24)}
 imageButton('assets/ui/guide_button.png',1510,25,125,105,openGuide); drawGames();
 let tray=allItems().filter(i=>i.plant.status==='tray');if(tray.length){let tw=220+Math.min(55,tray.length*3);imageButton('assets/ui/tray.png',30,730,tw,180,()=>{save.settings.last_inventory_filter='plants';screen='edit'});for(let n=0;n<Math.min(16,tray.length);n++){let s=flowerSheet(tray[n].plant.plant_type),sw=s.width/4,sh=s.height/2;ctx.drawImage(s,0,0,sw,sh,60+(n%8)*24,790-Math.floor(n/8)*30,sw*.23,sh*.23)}ctx.fillStyle='#fffbe4';ctx.strokeStyle='#304b31';ctx.lineWidth=5;ctx.font='bold 30px Georgia';ctx.textAlign='center';ctx.strokeText(`${tray.length} waiting`,140,875);ctx.fillText(`${tray.length} waiting`,140,875)}
 imageButton('assets/ui/edit_button.png',1495,760,140,145,()=>screen='edit');}
function sortedGames(){return [...catalogue.minigames].sort((a,b)=>{let A=save.game_usage[a.id]||{},B=save.game_usage[b.id]||{};if(save.settings.minigame_sort==='alpha')return a.id.localeCompare(b.id);if(save.settings.minigame_sort==='played')return (B.play_count||0)-(A.play_count||0);return (B.last_played||'').localeCompare(A.last_played||'')})}
function drawGames(){let games=sortedGames();imageButton('assets/ui/cloud_carousel_left.png',220,170,165,174,()=>gameOffset=Math.max(0,gameOffset-1));games.slice(gameOffset,gameOffset+3).forEach((g,n)=>imageButton(g.icon,405+n*290,130,270,270,()=>play(g.id)));imageButton('assets/ui/cloud_carousel_right.png',1280,170,165,174,()=>gameOffset=Math.min(Math.max(0,games.length-3),gameOffset+1))}
function play(id){let game=catalogue.minigames.find(g=>g.id===id);if(!game?.entrypoint){message=`${game?.title||names(id)} is not available yet.`;return}let session=buildGameSession(game);if(!session.items.length){message='No compatible learning items are available.\nStart or activate a learning pack first.';return}activeGameSession={game,session,applied:false};let frame=document.querySelector('#minigame-frame'),dialog=document.querySelector('#minigame-dialog');frame.src=game.entrypoint;dialog.hidden=false;frame.onload=()=>frame.contentWindow.postMessage({type:'knowledge-bloom:session',session},location.origin)}
function selectedItems(){let s=save.settings.selected_pack_scope;if(s==='all_everything')return allItems();if(s==='all_active')return Object.entries(save.pack_progress).filter(([,p])=>p.status==='active').flatMap(([,p])=>p.items);return save.pack_progress[s]?.items||[]}

function scopedPacks(){let scope=save.settings.selected_pack_scope,entries=catalogue.packs.filter(p=>save.pack_progress[p.id]);if(scope==='all_active')return entries.filter(p=>save.pack_progress[p.id].status==='active');if(scope==='all_everything')return entries;return entries.filter(p=>p.id===scope)}
function contentFor(pack,item){let path=value=>value?new URL(`packs/${pack.id}/${value}`,document.baseURI).href:null,q=item.question||{},a=item.answer||{},ex=item.explanation||{};return {question:{...q,image:path(q.image),audio:path(q.audio),video:path(q.video)},answer:{...a,image:path(a.image),audio:path(a.audio),video:path(a.video)},explanation:{...ex,image:path(ex.image),audio:path(ex.audio),video:path(ex.video)}}}
function safeDistractors(item,allSource){let accepted=new Set([item.answer?.text,...(item.answer?.accepted_answers||[])].filter(Boolean).map(normalAnswer)),excluded=new Set((item.distractor_exclusions||[]).map(normalAnswer)),values=[...(item.distractors||[]),...allSource.map(x=>x.answer?.text)];return [...new Map(values.filter(Boolean).map(x=>[normalAnswer(x),x])).entries()].filter(([key])=>!accepted.has(key)&&!excluded.has(key)).map(([,value])=>value).slice(0,3)}
function buildGameSession(game){let now=Date.now(),packs=scopedPacks(),sourceByPack=new Map(packs.map(pack=>[pack.id,pack.items||[]])),existing=[];for(let pack of packs){let progress=save.pack_progress[pack.id];for(let item of progress.items||[]){let source=(pack.items||[]).find(x=>x.item_id===item.item_id);if(!source?.question||!source?.answer?.text)continue;let due=now>=Date.parse(item.next_review_at),priority=(due?100:0)+(item.difficulty||.5)*10+(item.practice_fail_pressure||0)*4-(item.mastery||0)*3;existing.push({pack,source,progress:item,due,priority})}}existing.sort((a,b)=>b.priority-a.priority);let maximum=save.settings.round_size||10,chosen=existing.slice(0,maximum),newSlots=Math.min(save.settings.max_new_introductions??3,maximum-chosen.filter(x=>x.due).length),newItems=[];for(let pack of packs.filter(p=>save.pack_progress[p.id].status==='active')){let known=new Set((save.pack_progress[pack.id].items||[]).map(x=>x.item_id));for(let source of pack.items||[])if(!known.has(source.item_id)&&source.question&&source.answer?.text)newItems.push({pack,source})}newItems=newItems.slice(0,newSlots);chosen=chosen.slice(0,maximum-newItems.length);let selected=[...chosen.map(x=>({...x,interaction_type:x.due?'valid_review':'practice'})),...newItems.map(x=>({...x,interaction_type:'introduction'}))];selected.sort(()=>Math.random()-.5);let allSource=[...sourceByPack.values()].flat();return {session_schema_version:'1.0',session_id:`session_${Date.now()}_${crypto.randomUUID().slice(0,8)}`,game_id:game.id,user_id:activeUserId,started_at:new Date().toISOString(),pack_scope:{mode:save.settings.selected_pack_scope,pack_ids:packs.map(p=>p.id)},settings:{round_size:maximum,answer_mode:'multiple_choice',max_wrong_attempts:3,max_new_introductions:save.settings.max_new_introductions??3},items:selected.map(x=>({pack_id:x.pack.id,item_id:x.source.item_id,interaction_type:x.interaction_type,content:contentFor(x.pack,x.source),distractors:safeDistractors(x.source,allSource),comparison:x.source.answer?.comparison||x.pack.answer_comparison||{},session_metadata:{is_due:x.interaction_type==='valid_review',is_new:x.interaction_type==='introduction'}}))}}
function normalAnswer(value){return String(value??'').normalize('NFKC').trim().toLocaleLowerCase().replace(/[.!?,;:]+$/g,'')}

function validateGameResult(result){let active=activeGameSession,s=active?.session;if(!active||active.applied||result?.result_schema_version!=='1.0'||result.session_id!==s.session_id||result.game_id!==s.game_id||result.user_id!==s.user_id||result.round_completed!==true)return false;if(!Array.isArray(result.results)||result.results.length!==s.items.length)return false;let expected=new Map(s.items.map(i=>[`${i.pack_id}:${i.item_id}`,i])),seen=new Set();for(let r of result.results){let key=`${r.pack_id}:${r.item_id}`,item=expected.get(key),introValid=item?.interaction_type!=='introduction'||(r.introduction?.teaching_card_shown===true&&r.introduction?.attention_check_completed===r.finished_correctly);if(!item||seen.has(key)||r.interaction_type!==item.interaction_type||!introValid||!Array.isArray(r.attempts)||r.attempts.length<1||r.attempts.length>3||r.attempts.some(a=>typeof a?.correct!=='boolean')||r.first_attempt_correct!==r.attempts[0].correct||r.finished_correctly!==r.attempts.at(-1).correct||typeof r.deferred!=='boolean'||(r.deferred&&r.attempts.filter(a=>!a.correct).length!==3))return false;seen.add(key)}let summary=result.summary||{},first=result.results.filter(r=>r.first_attempt_correct).length,finished=result.results.filter(r=>r.finished_correctly).length,deferred=result.results.filter(r=>r.deferred).length,introduced=result.results.filter(r=>r.interaction_type==='introduction'&&r.finished_correctly).length;return summary.items_presented===result.results.length&&summary.first_attempt_correct===first&&summary.items_finished_correctly===finished&&summary.items_deferred===deferred&&summary.new_items_introduced===introduced}
function newProgress(packId,itemId,now){let assigned=save.pack_progress[packId]?.flower_reward_plan?.assignments?.[itemId];if(!assigned)throw new Error(`No saved flower assignment for ${packId}/${itemId}`);return {item_id:itemId,state:'new',lesson_status:'in_progress',lesson_started_at:now,lesson_completed_at:null,initial_check_attempts:[],introduced_at:now,last_seen_at:now,last_valid_review_at:null,next_review_at:new Date(Date.parse(now)+4*3600000).toISOString(),interval_hours:4,mastery:0,difficulty:.5,valid_review_count:0,review_count:0,lapse_count:0,recent_results:[],practice_fail_pressure:0,plant:{status:'locked',plant_type:assigned,pack_id:packId,item_id:itemId,row_id:null,x:null,depth:null}}}
function applyGardenPointRewards(result){let training=activeGameSession.session.items.every(item=>item.interaction_type==='practice'),awards=[{reason:training?'Round complete (training)':'Round complete',amount:training?GARDEN_POINT_REWARDS.training_round_completed:GARDEN_POINT_REWARDS.normal_round_completed}];for(let packId of new Set(result.results.map(r=>r.pack_id))){let pack=catalogue.packs.find(p=>p.id===packId),progress=save.pack_progress[packId],completed=pack?.items?.length>0&&pack.items.every(source=>progress.items.some(item=>item.item_id===source.item_id&&isLearned(item)));if(completed&&!save.rewards.completed_packs.includes(packId)){save.rewards.completed_packs.push(packId);awards.push({reason:'Completed a seed pack',amount:GARDEN_POINT_REWARDS.pack_completed})}}let total=awards.reduce((sum,a)=>sum+a.amount,0);save.rewards.garden_points+=total;save.rewards.lifetime_garden_points+=total;return {awards,total,balance:save.rewards.garden_points}}
function applyGameResult(result){if(!validateGameResult(result))return false;let now=result.ended_at&&Math.abs(Date.now()-Date.parse(result.ended_at))<86400000?result.ended_at:new Date().toISOString();for(let r of result.results){let pack=save.pack_progress[r.pack_id],item=(pack.items||[]).find(x=>x.item_id===r.item_id);if(!item){item=newProgress(r.pack_id,r.item_id,now);pack.items.push(item)}item.last_seen_at=now;let failures=r.attempts.filter(a=>!a.correct).length;if(r.interaction_type==='introduction'){item.initial_check_attempts=r.attempts.map(a=>a.correct);item.difficulty=Math.min(.9,.5+failures*.12);item.interval_hours=Math.max(1,4-failures);item.next_review_at=new Date(Date.parse(now)+item.interval_hours*3600000).toISOString();if(r.finished_correctly){item.lesson_status='completed';item.lesson_completed_at=now;item.state='learning';item.plant.status='tray'}}else if(r.interaction_type==='valid_review'){let success=r.first_attempt_correct;item.recent_results=[...(item.recent_results||[]),success?1:0].slice(-10);item.valid_review_count=(item.valid_review_count??item.review_count??0)+1;item.review_count=item.valid_review_count;item.last_valid_review_at=now;item.practice_fail_pressure=0;if(success){item.mastery=Math.min(1,(item.mastery||0)+.18);item.difficulty=Math.max(.1,(item.difficulty||.5)-.04);item.interval_hours=Math.max(4,Math.round((item.interval_hours||4)*(1.6+(1-item.difficulty))))}else{item.mastery=Math.max(0,(item.mastery||0)-.12);item.difficulty=Math.min(.9,(item.difficulty||.5)+.1+Math.max(0,failures-1)*.04);item.interval_hours=Math.max(1,Math.round((item.interval_hours||4)*.45));item.lapse_count=(item.lapse_count||0)+1}item.next_review_at=new Date(Date.parse(now)+item.interval_hours*3600000).toISOString();item.state=item.mastery>=.8?'mastered':item.mastery>=.45?'established':'learning'}else if(failures){item.practice_fail_pressure=(item.practice_fail_pressure||0)+failures;let remaining=Math.max(3600000,Date.parse(item.next_review_at)-Date.parse(now));item.next_review_at=new Date(Date.parse(now)+remaining/Math.min(4,1+failures)).toISOString()}}activeGameSession.applied=true;let u=save.game_usage[result.game_id]||{play_count:0,last_played:null};u.play_count++;u.last_played=now;save.game_usage[result.game_id]=u;activeGameSession.rewardSummary=applyGardenPointRewards(result);persist();return true}
function closeGame(){document.querySelector('#minigame-dialog').hidden=true;document.querySelector('#minigame-frame').src='about:blank';activeGameSession=null}
function drawPackCounts(counts,x,y,labels=false){let values=[counts.total,counts.seen,counts.complete],colors=['#202820','#4c8fb3','#9bcd83'],names=['Total','Seen','Complete'],centres=labels?[x,x+82,x+180]:[x,x+62,x+124];ctx.save();ctx.textAlign='center';ctx.textBaseline='alphabetic';ctx.font=`bold ${labels?26:21}px Georgia`;values.forEach((value,n)=>{ctx.fillStyle=colors[n];ctx.fillText(value,centres[n],y)});if(labels){ctx.font='bold 14px Georgia';names.forEach((label,n)=>{ctx.fillStyle=colors[n];ctx.fillText(label,centres[n],y+20)})}else{ctx.fillStyle='#52684a';ctx.fillText('–',x+31,y);ctx.fillText('–',x+93,y)}ctx.restore()}
function activePackCounts(){return catalogue.packs.filter(pack=>save.pack_progress[pack.id]?.status==='active').reduce((totals,pack)=>{let counts=packCardCounts(pack,save.pack_progress[pack.id]);totals.total+=counts.total;totals.seen+=counts.seen;totals.complete+=counts.complete;return totals},{total:0,seen:0,complete:0})}
function packs(){background();veil();drawPackCounts(activePackCounts(),55,48,true);title('Choose a learning pack',70);button(1355,25,275,58,'＋ Create New Pack',()=>dispatchEvent(new CustomEvent('open-pack-editor')),{active:true,size:20});catalogue.packs.forEach((p,n)=>{let y=105+n*265,progress=save.pack_progress[p.id];ctx.fillStyle='#fff9e9e8';round(180,y,1310,235,28);ctx.fill();ctx.drawImage(img.get(p.icon),210,y+17,205,205);ctx.fillStyle='#34482f';ctx.textAlign='left';ctx.font='bold 34px Georgia';ctx.fillText(p.title||names(p.id),450,y+55);ctx.font='21px Georgia';wrapText(p.subtitle||p.description||'Learning pack',450,y+92,650,29);drawPackCounts(packCardCounts(p,progress),450,y+172);let label=!progress?'Start pack':progress.status==='paused'?'Paused':'Active';button(1215,y+38,220,64,label,()=>togglePack(p),{active:progress?.status==='active'});button(1215,y+125,220,58,'View pack',()=>openPack(p),{size:20})});button(35,865,150,55,'Back',()=>screen='home')}
function wrapText(text,x,y,maxWidth,lineHeight){let line='';for(const word of String(text).split(/\s+/)){let test=line?`${line} ${word}`:word;if(line&&ctx.measureText(test).width>maxWidth){ctx.fillText(line,x,y);y+=lineHeight;line=word}else line=test}if(line)ctx.fillText(line,x,y)}
function togglePack(pack){let id=pack.id,progress=save.pack_progress[id];if(progress){progress.status=progress.status==='active'?'paused':'active';if(progress.status==='active')save.settings.selected_pack_scope=id;persist();return}openFlowerPlan(pack)}

function openFlowerPlan(pack){let dialog=document.querySelector('#flower-plan-dialog'),choices=createFlowerChoices(pack.items||[],catalogue.flowers.map(f=>f.id));dialog.hidden=false;dialog.dataset.packId=pack.id;document.querySelector('#flower-plan-icon').src=pack.icon;document.querySelector('#flower-plan-icon').alt=`${pack.title||names(pack.id)} pack icon`;document.querySelector('#flower-plan-title').textContent=pack.title||names(pack.id);document.querySelector('#flower-plan-description').textContent=pack.description||pack.subtitle||'A new learning adventure';document.querySelector('#flower-plan-count').textContent=`${pack.items?.length||0} learning items · ${pack.items?.length||0} memory flowers`;document.querySelector('#flower-plan-choices').replaceChildren(...choices.map((plan,index)=>{let button=document.createElement('button');button.className='flower-plan-choice';button.type='button';button.setAttribute('aria-label',`Flower reward choice ${index+1}`);let shown=plan.species.length===1?Array(4).fill(plan.species[0]):plan.species,scale=Math.min(1,5/shown.length);shown.forEach((id,n)=>{let sprite=document.createElement('canvas'),sheet=flowerSheet(id),sw=sheet.width/4,sh=sheet.height/2;sprite.width=92;sprite.height=142;let c=sprite.getContext('2d'),factor=Math.min(sprite.width/sw,sprite.height/sh)*scale,w=sw*factor,h=sh*factor;c.drawImage(sheet,3*sw,0,sw,sh,(sprite.width-w)/2,sprite.height-h,w,h);sprite.style.left=`calc(50% - 46px + ${(n-(shown.length-1)/2)*Math.min(34,135/Math.max(1,shown.length-1))}px)`;button.append(sprite)});let label=document.createElement('span');label.textContent='Choose this field';button.append(label);button.onclick=()=>activateWithFlowerPlan(pack,plan);return button}))}
function activateWithFlowerPlan(pack,plan){save.pack_progress[pack.id]={status:'active',installed_version:pack.version||'1.0.0',introduced_count:0,next_item_index:0,items:[],flower_reward_plan:plan};save.settings.selected_pack_scope=pack.id;document.querySelector('#flower-plan-dialog').hidden=true;message=`${pack.title||names(pack.id)} is ready!\nPlay Flashcards to begin learning.`;persist()}
function valueText(value){if(Array.isArray(value))return value.join(', ');if(value&&typeof value==='object')return Object.entries(value).map(([k,v])=>`${names(k)}: ${valueText(v)}`).join(' · ');return String(value)}
function openPack(pack){let dialog=document.querySelector('#pack-dialog');dialog.hidden=false;document.querySelector('#pack-dialog-icon').src=pack.icon;document.querySelector('#pack-dialog-icon').alt=`${pack.title||names(pack.id)} pack icon`;document.querySelector('#pack-dialog-title').textContent=pack.title||names(pack.id);document.querySelector('#pack-dialog-subtitle').textContent=pack.description||pack.subtitle||'';let metadata={Subtitle:pack.subtitle,Author:pack.author,Version:pack.version,Language:pack.language,Items:pack.items?.length,Tags:pack.tags,License:pack.license};document.querySelector('#pack-metadata').replaceChildren(...Object.entries(metadata).filter(([,v])=>v!=null&&valueText(v)).flatMap(([key,value])=>{let dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=key;dd.textContent=valueText(value);return[dt,dd]}));document.querySelector('#show-pack-context').checked=false;renderPackItems(pack);dialog.dataset.packId=pack.id}
function renderPackItems(pack){let full=document.querySelector('#show-pack-context').checked,container=document.querySelector('#pack-items');container.replaceChildren(...(pack.items||[]).map(item=>{let article=document.createElement('article'),question=item.question||{},answer=item.answer||{};article.className=`pack-item${question.image?'':' no-image'}`;if(question.image){let image=document.createElement('img');image.src=`packs/${pack.id}/${question.image}`;image.alt=answer.text||item.item_id;article.append(image)}let body=document.createElement('div'),heading=document.createElement('h2'),answerLine=document.createElement('p');heading.textContent=question.text||item.item_id;answerLine.className='answer';answerLine.textContent=`Answer: ${answer.text||'—'}`;body.append(heading,answerLine);for(const [kind,symbol] of [['audio','🔊'],['video','▶️']])if(question[kind]){let link=document.createElement('a');link.className='media-link';link.href=`packs/${pack.id}/${question[kind]}`;link.textContent=`${symbol} Open ${kind}`;link.target='_blank';body.append(document.createElement('br'),link)}if(full){let context=document.createElement('div'),dl=document.createElement('dl');context.className='item-context';let fields={Item:item.item_id,Category:question.category,'Accepted answers':answer.accepted_answers,Distractors:item.distractors,Explanation:item.explanation?.text,Tags:item.tags,'Question credit':question.credit};for(const [key,value] of Object.entries(fields))if(value!=null&&valueText(value)){let dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=key;dd.textContent=valueText(value);dl.append(dt,dd)}context.append(dl);body.append(context)}article.append(body);return article}))}
async function loadUsers(preferred){let response=await fetch('/api/users').then(r=>r.json()).catch(()=>({users:[]}));userList=response.users||[];activeUserId=preferred||response.active_user_id||userList[0]?.user_id;if(!activeUserId){let created=await createUser('Garden Learner',false);activeUserId=created.user_id}await switchUser(activeUserId)}
async function createUser(suggested='',ask=true){let displayName=ask?prompt('Name for the new learner:',suggested):suggested;if(!displayName)return null;let initial=fresh();initial.profile={display_name:displayName};let created=await fetch('/api/users',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({display_name:displayName,save:initial})}).then(r=>r.json());userList.push(created);return created}
async function switchUser(userId){let loaded=await fetch(`/api/save?user=${userId}`).then(r=>r.json()).catch(()=>null);activeUserId=userId;save=loaded||fresh();save.profile??={display_name:userList.find(u=>u.user_id===userId)?.display_name||'Garden Learner'};normaliseSave();syncUserSelect();persist()}
function syncUserSelect(){let select=document.querySelector('#user-select');select.replaceChildren(...userList.map(user=>new Option(user.display_name,user.user_id,user.user_id===activeUserId,user.user_id===activeUserId)))}
function normaliseSave(){save.settings??=fresh().settings;save.rewards??={garden_points:0,lifetime_garden_points:0,highest_unlocked_tier:1,tier_purchase_counts:{},completed_packs:[]};save.rewards.garden_points??=0;save.rewards.lifetime_garden_points??=save.rewards.garden_points;save.rewards.highest_unlocked_tier??=1;save.rewards.tier_purchase_counts??={};save.rewards.completed_packs??=[];save.settings.background??='assets/backgrounds/field.png';save.settings.horizon??=.5;save.settings.row_count??=6;save.settings.debug_mode??=false;save.pack_progress??={};save.inventory??={furniture:[],decorative_plants:[]};save.inventory.furniture??=[];for(let pack of catalogue.packs){let progress=save.pack_progress[pack.id];if(!progress)continue;if(!progress.flower_reward_plan){let existing=Object.fromEntries((progress.items||[]).map(item=>[item.item_id,item.plant?.plant_type]).filter(([,type])=>type));progress.flower_reward_plan={selection_type:'balanced',species:[...new Set(Object.values(existing))],assignments:existing}}expandFlowerPlan(progress.flower_reward_plan,pack.items||[],catalogue.flowers.map(f=>f.id));for(let item of progress.items||[]){item.plant.pack_id??=pack.id;item.plant.item_id??=item.item_id}}}
function advanceTime(hours){let offset=hours*3600000,isoDate=/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:Z|[+-]\d{2}:\d{2})$/;function shift(value){if(typeof value==='string'&&isoDate.test(value)){let timestamp=Date.parse(value);return Number.isNaN(timestamp)?value:new Date(timestamp-offset).toISOString()}if(Array.isArray(value))return value.map(shift);if(value&&typeof value==='object')for(let key of Object.keys(value))value[key]=shift(value[key]);return value}shift(save);persist()}
function openGuide(){document.querySelector('#guide').hidden=false;syncGuideSettings()}
function closeGuide(){document.querySelector('#guide').hidden=true;document.querySelector('#guide-settings-panel').hidden=true;document.querySelector('#guide-settings').ariaExpanded='false'}
function syncGuideSettings(){syncUserSelect();let bg=activeBackground(),h=Math.round((save.settings.horizon??.5)*100),rows=save.settings.row_count||6,select=document.querySelector('#background-select');document.querySelector('#minigame-sort-select').value=save.settings.minigame_sort||'recent';document.querySelector('#debug-mode-toggle').checked=save.settings.debug_mode===true;select.replaceChildren(...catalogue.backgrounds.map(b=>new Option(names(b.id),b.image,b.image===bg,b.image===bg)));document.querySelector('#background-preview').src=bg;document.querySelector('#horizon-slider').value=h;document.querySelector('#horizon-value').value=`${h}%`;document.querySelector('#horizon-line').style.top=`${h}%`;document.querySelector('#row-count-slider').value=rows;document.querySelector('#row-count-value').value=`${rows} rows`}
function editor(){background();drawObjects(save.garden.focused_row,editorMode==='move'||editorMode==='place');drawHeld();ctx.fillStyle='#ffffffc9';round(20,14,1632,200,28);ctx.fill();['plants','furniture','all'].forEach((f,n)=>button(40+n*190,25,170,42,names(f),()=>{cancelHeld();editorMode=null;save.settings.last_inventory_filter=f;inventoryOffset=0;persist()},{active:save.settings.last_inventory_filter===f,size:18}));inventory();
 let off=fn=>()=>{cancelHeld();editorMode=null;fn()};button(35,230,155,52,'Place Items',()=>toggleMode('place'),{active:editorMode==='place',size:19});button(200,230,160,52,'Scatter Plants',off(scatter),{size:18});button(370,230,145,52,'Move Plants',()=>toggleMode('move'),{active:editorMode==='move',size:18});button(535,230,142,52,'Previous Row',off(()=>focus(-1)),{size:17});button(687,230,118,52,'Next Row',off(()=>focus(1)),{size:17});button(815,230,168,52,'Newest Row',off(()=>{save.garden.focused_row=save.garden.rows.at(-1).id;persist()}),{size:17});button(993,230,145,52,'Clear Row',off(confirmClear),{size:17});button(1160,230,120,52,'Shop',off(()=>{screen='shop';shopOffset=0;shopTierOffsets={}}),{active:true,size:19});drawPointsCounter(1290,230);button(1500,230,135,52,'Done',off(()=>{screen='home';persist()}));
 if(editorMode){ctx.fillStyle='#fff9df';ctx.font='bold 21px Georgia';ctx.textAlign='center';let instructions=held?`${editorMode==='move'?'Moving':'Placing'} ${itemName(held)} — click to place · mouse wheel to resize · right-click to inventory`:{place:'Choose an inventory item to place',move:'Click a garden item to move it'}[editorMode];ctx.fillText(instructions,W/2,330)}if(confirmation)drawConfirmation()}
function drawPointsCounter(x,y){ctx.save();ctx.fillStyle='#dceba9';ctx.strokeStyle='#55723c';ctx.lineWidth=3;round(x,y,190,52,26);ctx.fill();ctx.stroke();ctx.fillStyle='#315632';ctx.font='bold 21px Georgia';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(`🍃 ${save.rewards.garden_points}`,x+95,y+26);ctx.restore()}
function ownedQuantity(itemId){return save.inventory.furniture.filter(item=>item.item_id===itemId).length}
function buyFurniture(item){if(item.tier>save.rewards.highest_unlocked_tier){message=`Tier ${item.tier} is still locked.`;return}if(save.rewards.garden_points<item.price){message=`Not enough Garden Points.\nYou need ${item.price-save.rewards.garden_points} more.`;return}save.rewards.garden_points-=item.price;save.inventory.furniture.push({instance_id:`furniture_${crypto.randomUUID()}`,item_id:item.item_id,title:item.title,image:item.asset,tier:item.tier,status:'stored'});let counts=save.rewards.tier_purchase_counts;counts[item.tier]=(counts[item.tier]||0)+1;let next=item.tier+1,available=Math.min(catalogue.furniture_tier_count||1,next);if(next===available&&next>save.rewards.highest_unlocked_tier&&counts[item.tier]>=3){save.rewards.highest_unlocked_tier=next;message=`Tier ${next} furniture unlocked!`}else message=`${item.title} added to your inventory.`;persist()}
function shopTierMaxOffset(tier){let count=catalogue.furniture.filter(item=>item.tier===tier).length;return Math.max(0,(count-1)*195+160-640)}
function shop(){background();veil();title('Furniture Shop',65);drawPointsCounter(1400,28);button(35,25,145,55,'Back',()=>screen='edit');let tiers=[...Array(catalogue.furniture_tier_count||1)].map((_,n)=>n+1),start=shopOffset,end=Math.min(tiers.length,start+3);tiers.slice(start,end).forEach((tier,column)=>{let x=90+column*515,locked=tier>save.rewards.highest_unlocked_tier,offset=shopTierOffsets[tier]||0;ctx.fillStyle=locked?'#a8aa9be8':'#fff9e9ed';round(x,105,470,745,25);ctx.fill();ctx.fillStyle='#34482f';ctx.textAlign='center';ctx.font='bold 31px Georgia';ctx.fillText(`Tier ${tier}${locked?' — Locked':''}`,x+235,150);ctx.font='18px Georgia';if(locked)ctx.fillText(`Buy 3 items from Tier ${tier-1} to unlock`,x+235,180);else if(shopTierMaxOffset(tier))ctx.fillText('Scroll to browse all items',x+235,180);ctx.save();ctx.beginPath();ctx.rect(x+10,190,450,640);ctx.clip();catalogue.furniture.filter(item=>item.tier===tier).forEach((item,n)=>{let y=205+n*195-offset,im=img.get(item.asset),scale=Math.min(150/im.width,100/im.height);ctx.drawImage(im,x+30+(150-im.width*scale)/2,y,im.width*scale,im.height*scale);ctx.textAlign='left';ctx.fillStyle='#34482f';ctx.font='bold 23px Georgia';ctx.fillText(item.title,x+205,y+28);ctx.font='19px Georgia';ctx.fillText(`🍃 ${item.price} points`,x+205,y+62);ctx.fillText(`Owned: ${ownedQuantity(item.item_id)}`,x+205,y+92);if(y+112>=190&&y+160<=830)button(x+205,y+112,205,48,locked?'Locked':save.rewards.garden_points<item.price?'Not enough points':'Purchase',()=>buyFurniture(item),{active:!locked&&save.rewards.garden_points>=item.price,size:17})});ctx.restore()});if(start>0)button(40,870,140,48,'Previous',()=>shopOffset=Math.max(0,shopOffset-3));if(end<tiers.length)button(1490,870,140,48,'Next',()=>shopOffset+=3)}
function itemKey(o){return o.plant?o.item_id:`furniture:${o.instance_id||o.id||o.item_id}`}
function itemName(o){return o.item_id||names(o.id)}
function inventoryItems(){let plants=allItems().filter(i=>i.plant.status==='tray'),furn=save.inventory.furniture.filter(f=>f.status==='stored'),order=save.settings.inventory_order||[];let rank=o=>{let n=order.indexOf(itemKey(o));return n<0?-1:n};plants.sort((a,b)=>rank(a)-rank(b));furn.sort((a,b)=>rank(a)-rank(b));let f=save.settings.last_inventory_filter;return f==='plants'?plants:f==='furniture'?furn:[...plants,...furn].sort((a,b)=>rank(a)-rank(b))}
function inventory(){let items=inventoryItems();imageButton('assets/ui/cloud_carousel_left.png',80,92,55,60,()=>inventoryOffset=Math.max(0,inventoryOffset-1));items.slice(inventoryOffset,inventoryOffset+9).forEach((o,n)=>{let x=155+n*145,y=76;ctx.drawImage(img.get('assets/ui/cloud_box.png'),x,y,125,105);let im=o.plant?flowerSheet(o.plant.plant_type):img.get(o.image);if(o.plant){let sw=im.width/4,sh=im.height/2;ctx.drawImage(im,stage(o)*sw,moisture(o)*sh,sw,sh,x+38,y+15,50,70)}else{let sc=Math.min(80/im.width,65/im.height);ctx.drawImage(im,x+62-im.width*sc/2,y+15,im.width*sc,im.height*sc)}hit.push({x,y,w:125,h:105,fn:()=>{editorMode='place';held=o}})});imageButton('assets/ui/cloud_carousel_right.png',1475,92,55,60,()=>inventoryOffset=Math.min(Math.max(0,items.length-9),inventoryOffset+1))}
function toggleMode(mode){if(editorMode===mode){cancelHeld();editorMode=null}else{cancelHeld();editorMode=mode;if(mode==='place')held=inventoryItems()[0]||null}}
function place(o,x,depth){if(o.plant){o.plant.status='planted';o.plant.row_id=save.garden.focused_row;o.plant.x=x;o.plant.depth=depth}else{o.status='placed';o.row_id=save.garden.focused_row;o.x=x;o.depth=depth}persist();held=editorMode==='place'?inventoryItems()[0]||null:null}
function depthAtY(y){let area=activeArea();return Math.max(0,Math.min(1,(area.bottom-y)/(area.bottom-area.top)))}
function clampedGroundPosition(x,y){let area=activeArea();return {x:Math.max(area.left,Math.min(area.right,x)),y:Math.max(area.top,Math.min(area.bottom,y))}}
function drawHeld(){if(!held||screen!=='edit')return;let ground=clampedGroundPosition(pointer.x,pointer.y),depth=depthAtY(ground.y);if(held.plant){let old=held.plant.depth;held.plant.depth=depth;flower(held,0,.5,true,ground.x,ground.y);held.plant.depth=old}else{let old=held.depth;held.depth=depth;drawFurniture(held,0,.5,ground.x,ground.y);held.depth=old}}
function scatter(){let candidates=allItems().filter(i=>i.plant.status==='tray'),furn=save.inventory.furniture.filter(f=>f.status==='placed'&&f.row_id===save.garden.focused_row);for(const [n,o] of candidates.entries()){for(let tries=0;tries<30;tries++){let x=.09+Math.random()*.82,d=.06+Math.random()*.86;if(furn.every(f=>Math.abs(f.x-x)>.10||d<f.depth-.1)){place(o,x,d);break}}}held=null;persist()}
function addRow(){let id=`row_${save.garden.rows.length+1}`;save.garden.rows.push({id,created_at:new Date().toISOString()});save.garden.focused_row=id;persist()}
function focus(d){let n=save.garden.rows.findIndex(r=>r.id===save.garden.focused_row);if(d>0&&n===save.garden.rows.length-1)return addRow();save.garden.focused_row=save.garden.rows[Math.max(0,Math.min(save.garden.rows.length-1,n+d))].id;persist()}
function cancelHeld(){held=null}
function returnToInventory(o){if(o.plant){o.plant.status='tray';o.plant.row_id=o.plant.x=o.plant.depth=null}else{o.status='stored';o.row_id=o.x=o.depth=null}let order=save.settings.inventory_order||(save.settings.inventory_order=[]),key=itemKey(o);save.settings.inventory_order=order.filter(x=>x!==key).concat(key);persist()}
function currentRowItems(){return rowItems(save.garden.focused_row)}
function gardenItemAt(x,y){let candidates=currentRowItems().map(o=>{if(o.plant){let sheet=flowerSheet(o.plant.plant_type),d=o.plant.depth,projection=rowProjection(d),scale=(o.plant.scale||1)*projection.scale,sw=sheet.width/4,sh=sheet.height/2,cx=o.plant.x*W,base=projection.y;return {o,depth:d,left:cx-sw*scale/2,right:cx+sw*scale/2,top:base-sh*scale,bottom:base}}let g=furnitureGeometry(o);return {o,depth:o.depth,left:g.x-g.w/2,right:g.x+g.w/2,top:g.y-g.h,bottom:g.y}}).filter(g=>x>=g.left&&x<=g.right&&y>=g.top&&y<=g.bottom).sort((a,b)=>a.depth-b.depth);return candidates[0]?.o||null}
function confirmClear(){confirmation={text:'Return every item in this row to your inventory?',yes:()=>{currentRowItems().forEach(returnToInventory);confirmation=null}}}
function drawConfirmation(){ctx.fillStyle='#263f2df2';round(480,350,712,230,30);ctx.fill();ctx.strokeStyle='#fff7d5';ctx.lineWidth=3;ctx.stroke();ctx.fillStyle='#fff7d5';ctx.font='bold 29px Georgia';ctx.textAlign='center';ctx.fillText('Clear this row?',W/2,415);ctx.font='21px Georgia';ctx.fillText(confirmation.text,W/2,462);button(650,505,155,48,'No',()=>confirmation=null);button(866,505,155,48,'Yes',confirmation.yes,{active:true})}
function veil(){ctx.fillStyle='#27452ca8';ctx.fillRect(0,0,W,H)}function title(t,y){ctx.fillStyle='#fff8d9';ctx.font='bold 42px Georgia';ctx.textAlign='center';ctx.fillText(t,W/2,y)}
async function persist(){if(!activeUserId)return;fetch(`/api/save?user=${activeUserId}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(save)}).catch(()=>localStorage.setItem('knowledge-bloom-save',JSON.stringify(save)))}
function frame(){hit.length=0;if(screen==='home')home();else if(screen==='packs')packs();else if(screen==='shop')shop();else editor();if(message){ctx.fillStyle='#263f2de8';round(530,370,610,205,30);ctx.fill();ctx.strokeStyle='#fff7d5';ctx.lineWidth=3;ctx.stroke();ctx.fillStyle='#fff7d5';ctx.font='bold 29px Georgia';ctx.textAlign='center';message.split('\n').forEach((l,n)=>ctx.fillText(l,W/2,425+n*42));button(750,525,172,44,'Lovely!',()=>message='')}requestAnimationFrame(frame)}
function eventPoint(e){let r=canvas.getBoundingClientRect(),scale=Math.min(r.width/W,r.height/H),ox=(r.width-W*scale)/2,oy=(r.height-H*scale)/2;return {x:(e.clientX-r.left-ox)/scale,y:(e.clientY-r.top-oy)/scale}}
canvas.addEventListener('pointermove',e=>pointer=eventPoint(e));canvas.addEventListener('click',e=>{let {x,y}=eventPoint(e);pointer={x,y};if(message){hit.at(-1)?.fn();return}let clickable=confirmation?hit.slice(-2):hit,h=[...clickable].reverse().find(b=>x>=b.x&&x<=b.x+b.w&&y>=b.y&&y<=b.y+b.h);if(h){h.fn();return}if(screen!=='edit'||confirmation)return;if(held){let ground=clampedGroundPosition(x,y);place(held,ground.x/W,depthAtY(ground.y));return}if(y<345)return;let o=gardenItemAt(x,y);if(o&&editorMode==='move')held=o});
canvas.addEventListener('contextmenu',e=>{if(screen!=='edit')return;e.preventDefault();let {x,y}=eventPoint(e),returned=held||(editorMode==='move'&&gardenItemAt(x,y));if(returned){returnToInventory(returned);held=editorMode==='place'?inventoryItems().find(o=>o!==returned)||null:null}});canvas.addEventListener('wheel',e=>{if(screen==='shop'){let {x,y}=eventPoint(e),column=Math.floor((x-90)/515),tier=shopOffset+column+1;if(column<0||column>2||y<105||y>850||tier>catalogue.furniture_tier_count)return;let max=shopTierMaxOffset(tier);if(!max)return;e.preventDefault();shopTierOffsets[tier]=Math.max(0,Math.min(max,(shopTierOffsets[tier]||0)+e.deltaY));return}if(screen!=='edit'||!held)return;e.preventDefault();let target=held.plant||held;target.scale=Math.max(.3,Math.min(3,(target.scale||1)*(e.deltaY<0?1.1:.9)))},{passive:false});addEventListener('keydown',e=>{if(e.key==='Escape'){cancelHeld();editorMode=null;confirmation=null}});
addEventListener('message',event=>{if(event.origin!==location.origin||event.source!==document.querySelector('#minigame-frame').contentWindow)return;if(event.data?.type==='knowledge-bloom:ready'&&activeGameSession)event.source.postMessage({type:'knowledge-bloom:session',session:activeGameSession.session},location.origin);if(event.data?.type==='knowledge-bloom:result'){let accepted=applyGameResult(event.data.result);event.source.postMessage({type:'knowledge-bloom:result-ack',accepted,consequences:accepted?{seeds_added:event.data.result.results.filter(r=>r.interaction_type==='introduction'&&r.finished_correctly).length,plants_updated:event.data.result.results.filter(r=>r.interaction_type==='valid_review').length,garden_points:activeGameSession.rewardSummary}:null},location.origin)}if(event.data?.type==='knowledge-bloom:close')closeGame()});
document.querySelector('#pack-dialog-close').addEventListener('click',()=>document.querySelector('#pack-dialog').hidden=true);
document.querySelector('#flower-plan-cancel').addEventListener('click',()=>document.querySelector('#flower-plan-dialog').hidden=true);
document.querySelector('#show-pack-context').addEventListener('change',()=>renderPackItems(catalogue.packs.find(p=>p.id===document.querySelector('#pack-dialog').dataset.packId)));
document.querySelector('#guide-close').addEventListener('click',closeGuide);
document.querySelector('#guide-settings').addEventListener('click',e=>{let panel=document.querySelector('#guide-settings-panel');panel.hidden=!panel.hidden;e.currentTarget.ariaExpanded=String(!panel.hidden)});
document.querySelector('#user-select').addEventListener('change',e=>switchUser(e.target.value));
document.querySelector('#add-user-button').addEventListener('click',async()=>{let user=await createUser();if(user)await switchUser(user.user_id)});
document.querySelector('#minigame-sort-select').addEventListener('change',e=>{save.settings.minigame_sort=e.target.value;gameOffset=0;persist()});
document.querySelector('#debug-mode-toggle').addEventListener('change',e=>{save.settings.debug_mode=e.target.checked;persist()});
document.querySelector('#background-select').addEventListener('change',async e=>{save.settings.background=e.target.value;if(!img.has(e.target.value))await load(e.target.value);syncGuideSettings();persist()});
document.querySelector('#background-import-button').addEventListener('click',()=>document.querySelector('#background-import').click());
document.querySelector('#background-import').addEventListener('change',async e=>{let file=e.target.files[0];if(!file)return;let response=await fetch('/api/backgrounds',{method:'POST',headers:{'Content-Type':file.type||'application/octet-stream','X-Filename':encodeURIComponent(file.name)},body:file});if(!response.ok){alert(`Import failed: ${await response.text()}`);return}let added=await response.json();catalogue.backgrounds.push(added);await load(added.image);save.settings.background=added.image;syncGuideSettings();persist();e.target.value=''});
document.querySelector('#horizon-slider').addEventListener('input',e=>{let value=Number(e.target.value);save.settings.horizon=value/100;document.querySelector('#horizon-value').value=`${value}%`;document.querySelector('#horizon-line').style.top=`${value}%`;persist()});
document.querySelector('#row-count-slider').addEventListener('input',e=>{save.settings.row_count=Number(e.target.value);document.querySelector('#row-count-value').value=`${e.target.value} rows`;persist()});
(async()=>{catalogue=await fetch('/api/catalogue').then(r=>r.json()).catch(()=>({packs:['animals','famous_art','ui_elements'].map(id=>({id,icon:`packs/${id}/icon.png`})),minigames:['flashcards','memorycards','memoryracer'].map(id=>({id,icon:`minigames/${id}/icon.png`})),flowers:['blue','poppy','purple','rose','yellow'].map(id=>({id,image:`assets/flowers/${id}.png`})),furniture:[],backgrounds:[{id:'field',image:'assets/backgrounds/field.png'}]}));await loadUsers();normaliseSave();catalogue.backgrounds??=[{id:'field',image:'assets/backgrounds/field.png'}];let assets=['assets/info/game_info.png',...catalogue.backgrounds.map(x=>x.image),...['new_pack_button','pack_left','pack_title_frame','pack_right','guide_button','cloud_carousel_left','cloud_carousel_right','tray','edit_button','cloud_box'].map(x=>`assets/ui/${x}.png`),...catalogue.packs.map(x=>x.icon),...catalogue.minigames.map(x=>x.icon),...catalogue.flowers.map(x=>x.image),...catalogue.furniture.map(x=>x.asset)];await Promise.all([...new Set(assets)].map(load));document.querySelector('#loading').remove();frame()})();
