const W=1672,H=941, canvas=document.querySelector('#garden'),ctx=canvas.getContext('2d');
const img=new Map(), hit=[]; let catalogue, screen='home', message='', held=null, inventoryOffset=0, gameOffset=0;
const names=s=>s.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase()).replace(/^Ui\b/,'UI');
const load=src=>new Promise((ok,bad)=>{const i=new Image();i.onload=()=>{img.set(src,i);ok(i)};i.onerror=bad;i.src=src});
const fresh=()=>({save_version:1,settings:{selected_pack_scope:'all_active',minigame_sort:'recent',last_inventory_filter:'plants',last_focused_row:'row_1'},pack_progress:{},garden:{rows:[{id:'row_1',created_at:new Date().toISOString()}],focused_row:'row_1'},inventory:{furniture:[],decorative_plants:[]},game_usage:{},prototype:{simulated_hours:0}});
let save=fresh();

function button(x,y,w,h,label,fn,opts={}){ctx.save();ctx.fillStyle=opts.active?'#496b43e8':'#fff9e5e8';ctx.strokeStyle='#5c6d43';ctx.lineWidth=3;round(x,y,w,h,14);ctx.fill();ctx.stroke();ctx.fillStyle=opts.active?'#fffbe6':'#35442e';ctx.font=`${opts.size||22}px Georgia`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(label,x+w/2,y+h/2);ctx.restore();hit.push({x,y,w,h,fn});}
function imageButton(src,x,y,w,h,fn,label=''){const i=img.get(src);if(i)ctx.drawImage(i,x,y,w,h);if(label){ctx.fillStyle='#fff4cf';ctx.font='bold 25px Georgia';ctx.textAlign='center';ctx.fillText(label,x+w/2,y+h/2+8)}hit.push({x,y,w,h,fn});}
function round(x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r)}
function background(){ctx.drawImage(img.get('assets/backgrounds/field.png'),0,0,W,H)}
function allItems(){return Object.values(save.pack_progress).flatMap(p=>p.items||[])}
function planted(){return allItems().filter(i=>i.plant.status==='planted')}
function stage(item){return Math.min(3,Math.floor(item.mastery*4.01))}
function moisture(item){return Date.now()+save.prototype.simulated_hours*3600000>=Date.parse(item.next_review_at)?1:0}
function flower(item,rowShift=0){const sheet=img.get(`assets/flowers/${item.plant.plant_type}.png`);if(!sheet)return;let d=Math.max(0,Math.min(1,item.plant.depth+rowShift*.25)),scale=.38+(1-d)*.56;let sw=sheet.width/4,sh=sheet.height/2,x=item.plant.x*W,y=900-d*330-rowShift*120;ctx.drawImage(sheet,stage(item)*sw,moisture(item)*sh,sw,sh,x-sw*scale/2,y-sh*scale,sw*scale,sh*scale)}
function drawObjects(){const focus=save.garden.rows.findIndex(r=>r.id===save.garden.focused_row);const visible=save.garden.rows.slice(0,focus+1);const objects=[];for(let ri=0;ri<visible.length;ri++){let id=visible[ri].id,shift=focus-ri;for(const it of planted().filter(i=>i.plant.row_id===id))objects.push({depth:it.plant.depth+shift,draw:()=>flower(it,shift)});for(const f of save.inventory.furniture.filter(f=>f.status==='placed'&&f.row_id===id)){let d=Math.min(1,f.depth+shift*.25),scale=.35+(1-d)*.55,im=img.get(f.image),x=f.x*W,y=900-d*330-shift*120;objects.push({depth:f.depth+shift,draw:()=>ctx.drawImage(im,x-im.width*scale/2,y-im.height*scale,im.width*scale,im.height*scale)})}}objects.sort((a,b)=>b.depth-a.depth).forEach(o=>o.draw())}
function home(){background();drawObjects();imageButton('assets/ui/new_pack_button.png',35,26,165,118,()=>screen='packs');
 let scopes=['All Active',...Object.entries(save.pack_progress).filter(([,p])=>p.status==='active').map(([id])=>names(id)),'All Everything'];let current=save.settings.selected_pack_scope==='all_active'?'All Active':save.settings.selected_pack_scope==='all_everything'?'All Everything':names(save.settings.selected_pack_scope);let cycle=d=>{let n=(scopes.indexOf(current)+d+scopes.length)%scopes.length;save.settings.selected_pack_scope=scopes[n]==='All Active'?'all_active':scopes[n]==='All Everything'?'all_everything':Object.keys(save.pack_progress).find(k=>names(k)===scopes[n]);persist()};
 imageButton('assets/ui/pack_left.png',520,25,65,78,()=>cycle(-1));imageButton('assets/ui/pack_title_frame.png',590,18,360,96,()=>{},current);imageButton('assets/ui/pack_right.png',955,25,65,78,()=>cycle(1));
 imageButton('assets/ui/guide_button.png',1510,25,125,105,()=>screen='guide'); drawGames();
 let tray=allItems().filter(i=>i.plant.status==='tray');if(tray.length){let tw=220+Math.min(55,tray.length*3);imageButton('assets/ui/tray.png',30,730,tw,180,()=>{save.settings.last_inventory_filter='plants';screen='edit'});for(let n=0;n<Math.min(16,tray.length);n++){let s=img.get(`assets/flowers/${tray[n].plant.plant_type}.png`),sw=s.width/4,sh=s.height/2;ctx.drawImage(s,0,0,sw,sh,60+(n%8)*24,790-Math.floor(n/8)*30,sw*.23,sh*.23)}ctx.fillStyle='#fffbe4';ctx.strokeStyle='#304b31';ctx.lineWidth=5;ctx.font='bold 30px Georgia';ctx.textAlign='center';ctx.strokeText(`${tray.length} waiting`,140,875);ctx.fillText(`${tray.length} waiting`,140,875)}
 imageButton('assets/ui/edit_button.png',1495,760,140,145,()=>screen='edit');}
function sortedGames(){return [...catalogue.minigames].sort((a,b)=>{let A=save.game_usage[a.id]||{},B=save.game_usage[b.id]||{};if(save.settings.minigame_sort==='alpha')return a.id.localeCompare(b.id);if(save.settings.minigame_sort==='played')return (B.play_count||0)-(A.play_count||0);return (B.last_played||'').localeCompare(A.last_played||'')})}
function drawGames(){let games=sortedGames();imageButton('assets/ui/cloud_carousel_left.png',1040,35,55,58,()=>gameOffset=Math.max(0,gameOffset-1));games.slice(gameOffset,gameOffset+3).forEach((g,n)=>imageButton(g.icon,1100+n*115,20,90,90,()=>play(g.id)));imageButton('assets/ui/cloud_carousel_right.png',1440,35,55,58,()=>gameOffset=Math.min(Math.max(0,games.length-3),gameOffset+1));button(1130,120,280,31,`Sort: ${{recent:'recently played',played:'most played',alpha:'alphabetical'}[save.settings.minigame_sort]}`,()=>{let s=['recent','played','alpha'];save.settings.minigame_sort=s[(s.indexOf(save.settings.minigame_sort)+1)%3];persist()},{size:16})}
function play(id){let u=save.game_usage[id]||{play_count:0,last_played:null};u.play_count++;u.last_played=new Date().toISOString();save.game_usage[id]=u;save.prototype.simulated_hours+=Math.max(6,u.play_count*4);let now=Date.now()+save.prototype.simulated_hours*3600000;let eligible=selectedItems().filter(i=>now>=Date.parse(i.next_review_at)).slice(0,10);eligible.forEach(i=>{i.review_count++;i.last_valid_review_at=new Date(now).toISOString();i.recent_results=[...i.recent_results,1].slice(-10);i.mastery=Math.min(1,i.mastery+.26);i.interval_hours=Math.round(i.interval_hours*2.2);i.next_review_at=new Date(now+i.interval_hours*3600000).toISOString()});message=`Round complete\nScore: ${eligible.length} / ${eligible.length}\nYour plants have been watered.`;persist()}
function selectedItems(){let s=save.settings.selected_pack_scope;if(s==='all_everything')return allItems();if(s==='all_active')return Object.entries(save.pack_progress).filter(([,p])=>p.status==='active').flatMap(([,p])=>p.items);return save.pack_progress[s]?.items||[]}
function packs(){background();veil();title('Choose a learning pack',90);catalogue.packs.forEach((p,n)=>{let y=170+n*180;ctx.fillStyle='#fff9e9e8';round(250,y,1170,145,28);ctx.fill();ctx.drawImage(img.get(p.icon),280,y+20,105,105);ctx.fillStyle='#34482f';ctx.textAlign='left';ctx.font='bold 32px Georgia';ctx.fillText(names(p.id),420,y+50);ctx.font='22px Georgia';ctx.fillText('Prototype learning pack with 25 items.',420,y+91);button(1160,y+40,210,65,save.pack_progress[p.id]?'Active':'Start pack',()=>activate(p.id),{active:!!save.pack_progress[p.id]})});button(70,840,150,55,'Back',()=>screen='home')}
function activate(id){if(!save.pack_progress[id]){let now=Date.now()+save.prototype.simulated_hours*3600000;save.pack_progress[id]={status:'active',introduced_count:10,items:Array.from({length:10},(_,n)=>({item_id:`${id}_${String(n+1).padStart(3,'0')}`,state:'learning',introduced_at:new Date(now).toISOString(),last_valid_review_at:null,next_review_at:new Date(now+4*3600000).toISOString(),interval_hours:4,mastery:0,difficulty:.5,review_count:0,lapse_count:0,recent_results:[],practice_fail_pressure:0,plant:{status:'tray',plant_type:catalogue.flowers[n%catalogue.flowers.length].id,row_id:null,x:null,depth:null}}))};save.settings.selected_pack_scope=id;message='Initial lesson preview complete!\nTen new memory seedlings are waiting in your tray.';screen='home';persist()}}
function guide(){background();veil();let g=img.get('assets/info/game_info.png'),scale=Math.min(1300/g.width,760/g.height);ctx.drawImage(g,(W-g.width*scale)/2,70,g.width*scale,g.height*scale);button(1450,40,150,55,'Close',()=>screen='home')}
function editor(){background();drawObjects();ctx.fillStyle='#ffffffc9';round(20,14,1632,235,28);ctx.fill();title(`Garden Editor · ${names(save.garden.focused_row)}`,45);['plants','furniture','all'].forEach((f,n)=>button(510+n*190,75,170,45,names(f),()=>{save.settings.last_inventory_filter=f;inventoryOffset=0;persist()},{active:save.settings.last_inventory_filter===f,size:18}));inventory();
 button(40,270,170,52,'Place Items',()=>held=inventoryItems()[0]||null,{active:!!held});button(225,270,170,52,'Scatter Plants',scatter);button(410,270,170,52,'Add New Row',addRow);button(595,270,150,52,'Previous Row',()=>focus(-1));button(760,270,130,52,'Next Row',()=>focus(1));button(905,270,220,52,'Newest Row',()=>{save.garden.focused_row=save.garden.rows.at(-1).id;persist()});button(1465,270,165,52,'Done',()=>{held=null;screen='home';persist()});
 if(held){ctx.fillStyle='#fff9df';ctx.font='bold 22px Georgia';ctx.textAlign='center';ctx.fillText(`Placing ${held.item_id||names(held.id)} — click the meadow · Esc to cancel`,W/2,350)}}
function inventoryItems(){let plants=allItems().filter(i=>i.plant.status==='tray'),furn=save.inventory.furniture.filter(f=>f.status==='stored');let f=save.settings.last_inventory_filter;return f==='plants'?plants:f==='furniture'?furn:[...plants,...furn]}
function inventory(){let items=inventoryItems();imageButton('assets/ui/cloud_carousel_left.png',80,105,55,60,()=>inventoryOffset=Math.max(0,inventoryOffset-1));items.slice(inventoryOffset,inventoryOffset+9).forEach((o,n)=>{let x=155+n*145;ctx.drawImage(img.get('assets/ui/cloud_box.png'),x,100,125,105);let im=o.plant?img.get(`assets/flowers/${o.plant.plant_type}.png`):img.get(o.image);if(o.plant){let sw=im.width/4,sh=im.height/2;ctx.drawImage(im,stage(o)*sw,moisture(o)*sh,sw,sh,x+38,115,50,70)}else{let sc=Math.min(80/im.width,65/im.height);ctx.drawImage(im,x+62-im.width*sc/2,115,im.width*sc,im.height*sc)}hit.push({x,y:100,w:125,h:105,fn:()=>held=o})});imageButton('assets/ui/cloud_carousel_right.png',1475,105,55,60,()=>inventoryOffset=Math.min(Math.max(0,items.length-9),inventoryOffset+1))}
function place(o,x,depth){if(o.plant){o.plant.status='planted';o.plant.row_id=save.garden.focused_row;o.plant.x=x;o.plant.depth=depth}else{o.status='placed';o.row_id=save.garden.focused_row;o.x=x;o.depth=depth}persist();held=inventoryItems()[0]||null}
function scatter(){let candidates=allItems().filter(i=>i.plant.status==='tray'),furn=save.inventory.furniture.filter(f=>f.status==='placed'&&f.row_id===save.garden.focused_row);for(const [n,o] of candidates.entries()){for(let tries=0;tries<30;tries++){let x=.09+Math.random()*.82,d=.06+Math.random()*.86;if(furn.every(f=>Math.abs(f.x-x)>.10||d<f.depth-.1)){place(o,x,d);break}}}held=null;persist()}
function addRow(){let id=`row_${save.garden.rows.length+1}`;save.garden.rows.push({id,created_at:new Date().toISOString()});save.garden.focused_row=id;persist()}
function focus(d){let n=save.garden.rows.findIndex(r=>r.id===save.garden.focused_row);save.garden.focused_row=save.garden.rows[Math.max(0,Math.min(save.garden.rows.length-1,n+d))].id;persist()}
function veil(){ctx.fillStyle='#27452ca8';ctx.fillRect(0,0,W,H)}function title(t,y){ctx.fillStyle='#fff8d9';ctx.font='bold 42px Georgia';ctx.textAlign='center';ctx.fillText(t,W/2,y)}
async function persist(){fetch('/api/save',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(save)}).catch(()=>localStorage.setItem('knowledge-bloom-save',JSON.stringify(save)))}
function frame(){hit.length=0;if(screen==='home')home();else if(screen==='packs')packs();else if(screen==='guide')guide();else editor();if(message){ctx.fillStyle='#263f2de8';round(530,370,610,205,30);ctx.fill();ctx.strokeStyle='#fff7d5';ctx.lineWidth=3;ctx.stroke();ctx.fillStyle='#fff7d5';ctx.font='bold 29px Georgia';ctx.textAlign='center';message.split('\n').forEach((l,n)=>ctx.fillText(l,W/2,425+n*42));button(750,525,172,44,'Lovely!',()=>message='')}requestAnimationFrame(frame)}
canvas.addEventListener('click',e=>{let r=canvas.getBoundingClientRect(),scale=Math.min(r.width/W,r.height/H),ox=(r.width-W*scale)/2,oy=(r.height-H*scale)/2,x=(e.clientX-r.left-ox)/scale,y=(e.clientY-r.top-oy)/scale;if(message){hit.at(-1)?.fn();return}let h=[...hit].reverse().find(b=>x>=b.x&&x<=b.x+b.w&&y>=b.y&&y<=b.y+b.h);if(h)h.fn();else if(screen==='edit'&&held&&y>370)place(held,Math.max(.02,Math.min(.98,x/W)),Math.max(0,Math.min(1,(900-y)/330)))});addEventListener('keydown',e=>{if(e.key==='Escape')held=null});
(async()=>{catalogue=await fetch('/api/catalogue').then(r=>r.json()).catch(()=>({packs:['animals','famous_art','ui_elements'].map(id=>({id,icon:`packs/${id}/icon.png`})),minigames:['flashcards','memorycards','memoryracer'].map(id=>({id,icon:`minigames/${id}/icon.png`})),flowers:['blue','poppy','purple','rose','yellow'].map(id=>({id,image:`assets/flowers/${id}.png`})),furniture:[]}));let remote=await fetch('/api/save').then(r=>r.json()).catch(()=>null),local=localStorage.getItem('knowledge-bloom-save');save=remote||(local&&JSON.parse(local))||fresh();if(!save.inventory.furniture.length)save.inventory.furniture=catalogue.furniture.map(f=>({...f,status:'stored'}));let assets=['assets/backgrounds/field.png','assets/info/game_info.png',...['new_pack_button','pack_left','pack_title_frame','pack_right','guide_button','cloud_carousel_left','cloud_carousel_right','tray','edit_button','cloud_box'].map(x=>`assets/ui/${x}.png`),...catalogue.packs.map(x=>x.icon),...catalogue.minigames.map(x=>x.icon),...catalogue.flowers.map(x=>x.image),...catalogue.furniture.map(x=>x.image)];await Promise.all([...new Set(assets)].map(load));document.querySelector('#loading').remove();frame()})();
