const W=1672,H=941, canvas=document.querySelector('#garden'),ctx=canvas.getContext('2d');
const img=new Map(), hit=[]; let catalogue, screen='home', message='', held=null, editorMode=null, inventoryOffset=0, gameOffset=0, pointer={x:W/2,y:H/2}, confirmation=null;
const names=s=>s.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase()).replace(/^Ui\b/,'UI');
const load=src=>new Promise((ok,bad)=>{const i=new Image();i.onload=()=>{img.set(src,i);ok(i)};i.onerror=bad;i.src=src});
const fresh=()=>({save_version:1,settings:{selected_pack_scope:'all_active',minigame_sort:'recent',last_inventory_filter:'plants',last_focused_row:'row_1',background:'assets/backgrounds/field.png',horizon:.5,row_count:6},pack_progress:{},garden:{rows:[{id:'row_1',created_at:new Date().toISOString()}],focused_row:'row_1'},inventory:{furniture:[],decorative_plants:[]},game_usage:{},prototype:{simulated_hours:0}});
let save=fresh();

function button(x,y,w,h,label,fn,opts={}){ctx.save();ctx.fillStyle=opts.active?'#496b43e8':'#fff9e5e8';ctx.strokeStyle='#5c6d43';ctx.lineWidth=3;round(x,y,w,h,14);ctx.fill();ctx.stroke();ctx.fillStyle=opts.active?'#fffbe6':'#35442e';ctx.font=`${opts.size||22}px Georgia`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(label,x+w/2,y+h/2);ctx.restore();hit.push({x,y,w,h,fn});}
function imageButton(src,x,y,w,h,fn,label=''){const i=img.get(src);if(i)ctx.drawImage(i,x,y,w,h);if(label){ctx.fillStyle='#fff4cf';ctx.font='bold 25px Georgia';ctx.textAlign='center';ctx.fillText(label,x+w/2,y+h/2+8)}hit.push({x,y,w,h,fn});}
function round(x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r)}
function activeBackground(){return save.settings.background||'assets/backgrounds/field.png'}
function background(){let image=img.get(activeBackground())||img.get('assets/backgrounds/field.png');ctx.drawImage(image,0,0,W,H)}
function allItems(){return Object.values(save.pack_progress).flatMap(p=>p.items||[])}
function planted(){return allItems().filter(i=>i.plant.status==='planted')}
function stage(item){return Math.min(3,Math.floor(item.mastery*4.01))}
function moisture(item){return Date.now()+save.prototype.simulated_hours*3600000>=Date.parse(item.next_review_at)?1:0}
function rowProjection(depth,rowShift=0){let baseY=900-depth*330,count=save.settings.row_count||6,t=Math.min(1,rowShift/count),horizon=(save.settings.horizon??.5)*H;return {y:horizon+(baseY-horizon)*(1-t),scale:1-.75*t}}
function flower(item,rowShift=0,alpha=1,finalStage=false,xOverride=null,yOverride=null){const sheet=img.get(`assets/flowers/${item.plant.plant_type}.png`);if(!sheet)return;let d=Math.max(0,Math.min(1,item.plant.depth)),projection=rowProjection(d,rowShift),scale=(.38+(1-d)*.56)*(item.plant.scale||1)*projection.scale;let sw=sheet.width/4,sh=sheet.height/2,x=xOverride??item.plant.x*W,y=yOverride??projection.y;ctx.save();ctx.globalAlpha=alpha;ctx.drawImage(sheet,(finalStage?3:stage(item))*sw,moisture(item)*sh,sw,sh,x-sw*scale/2,y-sh*scale,sw*scale,sh*scale);ctx.restore()}
function furnitureGeometry(f,rowShift=0,xOverride=null,yOverride=null){let d=Math.min(1,(f.depth??0)),projection=rowProjection(d,rowShift),scale=(.35+(1-d)*.55)*(f.scale||1)*projection.scale,im=img.get(f.image),x=xOverride??f.x*W,y=yOverride??projection.y;return {im,x,y,scale,w:im.width*scale,h:im.height*scale}}
function drawFurniture(f,rowShift=0,alpha=1,xOverride=null,yOverride=null){let g=furnitureGeometry(f,rowShift,xOverride,yOverride);ctx.save();ctx.globalAlpha=alpha;ctx.drawImage(g.im,g.x-g.w/2,g.y-g.h,g.w,g.h);ctx.restore()}
function rowItems(row){return [...planted().filter(i=>i.plant.row_id===row),...save.inventory.furniture.filter(f=>f.status==='placed'&&f.row_id===row)]}
function newestOccupiedRow(){return [...save.garden.rows].reverse().find(r=>rowItems(r.id).length)?.id||save.garden.rows.at(-1).id}
function activeArea(){return {left:W*.02,right:W*.98,top:570,bottom:900}}
function drawActiveArea(){let area=activeArea();ctx.save();ctx.fillStyle='#42a84633';ctx.strokeStyle='#287c3c99';ctx.lineWidth=3;ctx.fillRect(area.left,area.top,area.right-area.left,area.bottom-area.top);ctx.strokeRect(area.left,area.top,area.right-area.left,area.bottom-area.top);ctx.restore()}
function drawObjects(focusedRow=save.garden.focused_row,highlightActive=false){const focus=save.garden.rows.findIndex(r=>r.id===focusedRow),limit=(save.settings.row_count||6)+2,visible=save.garden.rows.slice(0,focus+1),behind=[],active=[];for(let ri=0;ri<visible.length;ri++){let id=visible[ri].id,shift=focus-ri;if(shift>limit)continue;let target=shift?behind:active,darken=draw=>()=>{ctx.save();ctx.filter='brightness(50%)';draw();ctx.restore()},effect=highlightActive&&shift?darken:draw=>draw;for(const it of planted().filter(i=>i.plant.row_id===id&&i!==held))target.push({depth:it.plant.depth+shift,draw:effect(()=>flower(it,shift))});for(const f of save.inventory.furniture.filter(f=>f.status==='placed'&&f.row_id===id&&f!==held))target.push({depth:f.depth+shift,draw:effect(()=>drawFurniture(f,shift))})}behind.sort((a,b)=>b.depth-a.depth).forEach(o=>o.draw());if(highlightActive)drawActiveArea();active.sort((a,b)=>b.depth-a.depth).forEach(o=>o.draw())}
function home(){background();drawObjects(newestOccupiedRow());imageButton('assets/ui/new_pack_button.png',35,26,165,118,()=>screen='packs');
 let scopes=['All Active',...Object.entries(save.pack_progress).filter(([,p])=>p.status==='active').map(([id])=>names(id)),'All Everything'];let current=save.settings.selected_pack_scope==='all_active'?'All Active':save.settings.selected_pack_scope==='all_everything'?'All Everything':names(save.settings.selected_pack_scope);let cycle=d=>{let n=(scopes.indexOf(current)+d+scopes.length)%scopes.length;save.settings.selected_pack_scope=scopes[n]==='All Active'?'all_active':scopes[n]==='All Everything'?'all_everything':Object.keys(save.pack_progress).find(k=>names(k)===scopes[n]);persist()};
 imageButton('assets/ui/pack_left.png',520,25,65,78,()=>cycle(-1));imageButton('assets/ui/pack_title_frame.png',590,18,360,96,()=>{},current);imageButton('assets/ui/pack_right.png',955,25,65,78,()=>cycle(1));
 imageButton('assets/ui/guide_button.png',1510,25,125,105,openGuide); drawGames();
 let tray=allItems().filter(i=>i.plant.status==='tray');if(tray.length){let tw=220+Math.min(55,tray.length*3);imageButton('assets/ui/tray.png',30,730,tw,180,()=>{save.settings.last_inventory_filter='plants';screen='edit'});for(let n=0;n<Math.min(16,tray.length);n++){let s=img.get(`assets/flowers/${tray[n].plant.plant_type}.png`),sw=s.width/4,sh=s.height/2;ctx.drawImage(s,0,0,sw,sh,60+(n%8)*24,790-Math.floor(n/8)*30,sw*.23,sh*.23)}ctx.fillStyle='#fffbe4';ctx.strokeStyle='#304b31';ctx.lineWidth=5;ctx.font='bold 30px Georgia';ctx.textAlign='center';ctx.strokeText(`${tray.length} waiting`,140,875);ctx.fillText(`${tray.length} waiting`,140,875)}
 imageButton('assets/ui/edit_button.png',1495,760,140,145,()=>screen='edit');}
function sortedGames(){return [...catalogue.minigames].sort((a,b)=>{let A=save.game_usage[a.id]||{},B=save.game_usage[b.id]||{};if(save.settings.minigame_sort==='alpha')return a.id.localeCompare(b.id);if(save.settings.minigame_sort==='played')return (B.play_count||0)-(A.play_count||0);return (B.last_played||'').localeCompare(A.last_played||'')})}
function drawGames(){let games=sortedGames();imageButton('assets/ui/cloud_carousel_left.png',220,170,165,174,()=>gameOffset=Math.max(0,gameOffset-1));games.slice(gameOffset,gameOffset+3).forEach((g,n)=>imageButton(g.icon,405+n*290,130,270,270,()=>play(g.id)));imageButton('assets/ui/cloud_carousel_right.png',1280,170,165,174,()=>gameOffset=Math.min(Math.max(0,games.length-3),gameOffset+1));button(696,415,280,31,`Sort: ${{recent:'recently played',played:'most played',alpha:'alphabetical'}[save.settings.minigame_sort]}`,()=>{let s=['recent','played','alpha'];save.settings.minigame_sort=s[(s.indexOf(save.settings.minigame_sort)+1)%3];persist()},{size:16})}
function play(id){let u=save.game_usage[id]||{play_count:0,last_played:null};u.play_count++;u.last_played=new Date().toISOString();save.game_usage[id]=u;save.prototype.simulated_hours+=Math.max(6,u.play_count*4);let now=Date.now()+save.prototype.simulated_hours*3600000;let eligible=selectedItems().filter(i=>now>=Date.parse(i.next_review_at)).slice(0,10);eligible.forEach(i=>{i.review_count++;i.last_valid_review_at=new Date(now).toISOString();i.recent_results=[...i.recent_results,1].slice(-10);i.mastery=Math.min(1,i.mastery+.26);i.interval_hours=Math.round(i.interval_hours*2.2);i.next_review_at=new Date(now+i.interval_hours*3600000).toISOString()});message=`Round complete\nScore: ${eligible.length} / ${eligible.length}\nYour plants have been watered.`;persist()}
function selectedItems(){let s=save.settings.selected_pack_scope;if(s==='all_everything')return allItems();if(s==='all_active')return Object.entries(save.pack_progress).filter(([,p])=>p.status==='active').flatMap(([,p])=>p.items);return save.pack_progress[s]?.items||[]}
function packs(){background();veil();title('Choose a learning pack',90);catalogue.packs.forEach((p,n)=>{let y=170+n*180;ctx.fillStyle='#fff9e9e8';round(250,y,1170,145,28);ctx.fill();ctx.drawImage(img.get(p.icon),280,y+20,105,105);ctx.fillStyle='#34482f';ctx.textAlign='left';ctx.font='bold 32px Georgia';ctx.fillText(names(p.id),420,y+50);ctx.font='22px Georgia';ctx.fillText('Prototype learning pack with 25 items.',420,y+91);button(1160,y+40,210,65,save.pack_progress[p.id]?'Active':'Start pack',()=>activate(p.id),{active:!!save.pack_progress[p.id]})});button(70,840,150,55,'Back',()=>screen='home')}
function activate(id){if(!save.pack_progress[id]){let now=Date.now()+save.prototype.simulated_hours*3600000;save.pack_progress[id]={status:'active',introduced_count:10,items:Array.from({length:10},(_,n)=>({item_id:`${id}_${String(n+1).padStart(3,'0')}`,state:'learning',introduced_at:new Date(now).toISOString(),last_valid_review_at:null,next_review_at:new Date(now+4*3600000).toISOString(),interval_hours:4,mastery:0,difficulty:.5,review_count:0,lapse_count:0,recent_results:[],practice_fail_pressure:0,plant:{status:'tray',plant_type:catalogue.flowers[n%catalogue.flowers.length].id,row_id:null,x:null,depth:null}}))};save.settings.selected_pack_scope=id;message='Initial lesson preview complete!\nTen new memory seedlings are waiting in your tray.';screen='home';persist()}}
function openGuide(){document.querySelector('#guide').hidden=false;syncGuideSettings()}
function closeGuide(){document.querySelector('#guide').hidden=true;document.querySelector('#guide-settings-panel').hidden=true;document.querySelector('#guide-settings').ariaExpanded='false'}
function syncGuideSettings(){let bg=activeBackground(),h=Math.round((save.settings.horizon??.5)*100),rows=save.settings.row_count||6,select=document.querySelector('#background-select');select.replaceChildren(...catalogue.backgrounds.map(b=>new Option(names(b.id),b.image,b.image===bg,b.image===bg)));document.querySelector('#background-preview').src=bg;document.querySelector('#horizon-slider').value=h;document.querySelector('#horizon-value').value=`${h}%`;document.querySelector('#horizon-line').style.top=`${h}%`;document.querySelector('#row-count-slider').value=rows;document.querySelector('#row-count-value').value=`${rows} rows`}
function editor(){background();drawObjects(save.garden.focused_row,editorMode==='move');drawHeld();ctx.fillStyle='#ffffffc9';round(20,14,1632,200,28);ctx.fill();['plants','furniture','all'].forEach((f,n)=>button(40+n*190,25,170,42,names(f),()=>{cancelHeld();editorMode=null;save.settings.last_inventory_filter=f;inventoryOffset=0;persist()},{active:save.settings.last_inventory_filter===f,size:18}));inventory();
 let off=fn=>()=>{cancelHeld();editorMode=null;fn()};button(35,230,155,52,'Place Items',()=>toggleMode('place'),{active:editorMode==='place',size:19});button(200,230,160,52,'Scatter Plants',off(scatter),{size:18});button(370,230,145,52,'Move Plants',()=>toggleMode('move'),{active:editorMode==='move',size:18});button(525,230,52,52,'−',()=>toggleMode('shrink'),{active:editorMode==='shrink',size:30});button(587,230,52,52,'+',()=>toggleMode('grow'),{active:editorMode==='grow',size:30});button(649,230,142,52,'Previous Row',off(()=>focus(-1)),{size:17});button(801,230,118,52,'Next Row',off(()=>focus(1)),{size:17});button(929,230,168,52,'Newest Row',off(()=>{save.garden.focused_row=save.garden.rows.at(-1).id;persist()}),{size:17});button(1107,230,145,52,'Clear Row',off(confirmClear),{size:17});button(1500,230,135,52,'Done',off(()=>{screen='home';persist()}));
 if(editorMode){ctx.fillStyle='#fff9df';ctx.font='bold 21px Georgia';ctx.textAlign='center';let instructions=held?`${editorMode==='move'?'Moving':'Placing'} ${itemName(held)} — click to place · right-click to inventory`:{place:'Choose an inventory item to place',move:'Click a garden item to move it',shrink:'Click a garden item to shrink it by 10%',grow:'Click a garden item to grow it by 10%'}[editorMode];ctx.fillText(instructions,W/2,330)}if(confirmation)drawConfirmation()}
function itemKey(o){return o.item_id||`furniture:${o.id}`}
function itemName(o){return o.item_id||names(o.id)}
function inventoryItems(){let plants=allItems().filter(i=>i.plant.status==='tray'),furn=save.inventory.furniture.filter(f=>f.status==='stored'),order=save.settings.inventory_order||[];let rank=o=>{let n=order.indexOf(itemKey(o));return n<0?-1:n};plants.sort((a,b)=>rank(a)-rank(b));furn.sort((a,b)=>rank(a)-rank(b));let f=save.settings.last_inventory_filter;return f==='plants'?plants:f==='furniture'?furn:[...plants,...furn].sort((a,b)=>rank(a)-rank(b))}
function inventory(){let items=inventoryItems();imageButton('assets/ui/cloud_carousel_left.png',80,92,55,60,()=>inventoryOffset=Math.max(0,inventoryOffset-1));items.slice(inventoryOffset,inventoryOffset+9).forEach((o,n)=>{let x=155+n*145,y=76;ctx.drawImage(img.get('assets/ui/cloud_box.png'),x,y,125,105);let im=o.plant?img.get(`assets/flowers/${o.plant.plant_type}.png`):img.get(o.image);if(o.plant){let sw=im.width/4,sh=im.height/2;ctx.drawImage(im,stage(o)*sw,moisture(o)*sh,sw,sh,x+38,y+15,50,70)}else{let sc=Math.min(80/im.width,65/im.height);ctx.drawImage(im,x+62-im.width*sc/2,y+15,im.width*sc,im.height*sc)}hit.push({x,y,w:125,h:105,fn:()=>{editorMode='place';held=o}})});imageButton('assets/ui/cloud_carousel_right.png',1475,92,55,60,()=>inventoryOffset=Math.min(Math.max(0,items.length-9),inventoryOffset+1))}
function toggleMode(mode){if(editorMode===mode){cancelHeld();editorMode=null}else{cancelHeld();editorMode=mode;if(mode==='place')held=inventoryItems()[0]||null}}
function place(o,x,depth){if(o.plant){o.plant.status='planted';o.plant.row_id=save.garden.focused_row;o.plant.x=x;o.plant.depth=depth}else{o.status='placed';o.row_id=save.garden.focused_row;o.x=x;o.depth=depth}persist();held=editorMode==='place'?inventoryItems()[0]||null:null}
function pointInActiveArea(x,y){let area=activeArea();return x>=area.left&&x<=area.right&&y>=area.top&&y<=area.bottom}
function drawHeld(){if(!held||screen!=='edit'||!pointInActiveArea(pointer.x,pointer.y))return;let depth=(900-pointer.y)/330;if(held.plant){let old=held.plant.depth;held.plant.depth=depth;flower(held,0,.5,true,pointer.x,pointer.y);held.plant.depth=old}else{let old=held.depth;held.depth=depth;drawFurniture(held,0,.5,pointer.x,pointer.y);held.depth=old}}
function scatter(){let candidates=allItems().filter(i=>i.plant.status==='tray'),furn=save.inventory.furniture.filter(f=>f.status==='placed'&&f.row_id===save.garden.focused_row);for(const [n,o] of candidates.entries()){for(let tries=0;tries<30;tries++){let x=.09+Math.random()*.82,d=.06+Math.random()*.86;if(furn.every(f=>Math.abs(f.x-x)>.10||d<f.depth-.1)){place(o,x,d);break}}}held=null;persist()}
function addRow(){let id=`row_${save.garden.rows.length+1}`;save.garden.rows.push({id,created_at:new Date().toISOString()});save.garden.focused_row=id;persist()}
function focus(d){let n=save.garden.rows.findIndex(r=>r.id===save.garden.focused_row);if(d>0&&n===save.garden.rows.length-1)return addRow();save.garden.focused_row=save.garden.rows[Math.max(0,Math.min(save.garden.rows.length-1,n+d))].id;persist()}
function cancelHeld(){held=null}
function returnToInventory(o){if(o.plant){o.plant.status='tray';o.plant.row_id=o.plant.x=o.plant.depth=null}else{o.status='stored';o.row_id=o.x=o.depth=null}let order=save.settings.inventory_order||(save.settings.inventory_order=[]),key=itemKey(o);save.settings.inventory_order=order.filter(x=>x!==key).concat(key);persist()}
function currentRowItems(){return rowItems(save.garden.focused_row)}
function gardenItemAt(x,y){let candidates=currentRowItems().map(o=>{if(o.plant){let sheet=img.get(`assets/flowers/${o.plant.plant_type}.png`),d=o.plant.depth,scale=(.38+(1-d)*.56)*(o.plant.scale||1),sw=sheet.width/4,sh=sheet.height/2,cx=o.plant.x*W,base=900-d*330;return {o,depth:d,left:cx-sw*scale/2,right:cx+sw*scale/2,top:base-sh*scale,bottom:base}}let g=furnitureGeometry(o);return {o,depth:o.depth,left:g.x-g.w/2,right:g.x+g.w/2,top:g.y-g.h,bottom:g.y}}).filter(g=>x>=g.left&&x<=g.right&&y>=g.top&&y<=g.bottom).sort((a,b)=>a.depth-b.depth);return candidates[0]?.o||null}
function confirmClear(){confirmation={text:'Return every item in this row to your inventory?',yes:()=>{currentRowItems().forEach(returnToInventory);confirmation=null}}}
function drawConfirmation(){ctx.fillStyle='#263f2df2';round(480,350,712,230,30);ctx.fill();ctx.strokeStyle='#fff7d5';ctx.lineWidth=3;ctx.stroke();ctx.fillStyle='#fff7d5';ctx.font='bold 29px Georgia';ctx.textAlign='center';ctx.fillText('Clear this row?',W/2,415);ctx.font='21px Georgia';ctx.fillText(confirmation.text,W/2,462);button(650,505,155,48,'No',()=>confirmation=null);button(866,505,155,48,'Yes',confirmation.yes,{active:true})}
function veil(){ctx.fillStyle='#27452ca8';ctx.fillRect(0,0,W,H)}function title(t,y){ctx.fillStyle='#fff8d9';ctx.font='bold 42px Georgia';ctx.textAlign='center';ctx.fillText(t,W/2,y)}
async function persist(){fetch('/api/save',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(save)}).catch(()=>localStorage.setItem('knowledge-bloom-save',JSON.stringify(save)))}
function frame(){hit.length=0;if(screen==='home')home();else if(screen==='packs')packs();else editor();if(message){ctx.fillStyle='#263f2de8';round(530,370,610,205,30);ctx.fill();ctx.strokeStyle='#fff7d5';ctx.lineWidth=3;ctx.stroke();ctx.fillStyle='#fff7d5';ctx.font='bold 29px Georgia';ctx.textAlign='center';message.split('\n').forEach((l,n)=>ctx.fillText(l,W/2,425+n*42));button(750,525,172,44,'Lovely!',()=>message='')}requestAnimationFrame(frame)}
function eventPoint(e){let r=canvas.getBoundingClientRect(),scale=Math.min(r.width/W,r.height/H),ox=(r.width-W*scale)/2,oy=(r.height-H*scale)/2;return {x:(e.clientX-r.left-ox)/scale,y:(e.clientY-r.top-oy)/scale}}
canvas.addEventListener('pointermove',e=>pointer=eventPoint(e));canvas.addEventListener('click',e=>{let {x,y}=eventPoint(e);pointer={x,y};if(message){hit.at(-1)?.fn();return}let clickable=confirmation?hit.slice(-2):hit,h=[...clickable].reverse().find(b=>x>=b.x&&x<=b.x+b.w&&y>=b.y&&y<=b.y+b.h);if(h){h.fn();return}if(screen!=='edit'||confirmation||y<345)return;if(held){if(pointInActiveArea(x,y))place(held,x/W,(900-y)/330);return}let o=gardenItemAt(x,y);if(!o)return;if(editorMode==='move')held=o;else if(editorMode==='grow'||editorMode==='shrink'){let target=o.plant?o.plant:o;target.scale=Math.max(.3,Math.min(3,(target.scale||1)*(editorMode==='grow'?1.1:.9)));persist()}});
canvas.addEventListener('contextmenu',e=>{if(screen!=='edit')return;e.preventDefault();let {x,y}=eventPoint(e),returned=held||(editorMode==='move'&&gardenItemAt(x,y));if(returned){returnToInventory(returned);held=editorMode==='place'?inventoryItems().find(o=>o!==returned)||null:null}});canvas.addEventListener('wheel',e=>{if(screen!=='edit'||!held||held.plant)return;e.preventDefault();held.scale=Math.max(.3,Math.min(3,(held.scale||1)*(e.deltaY<0?1.1:.9)))},{passive:false});addEventListener('keydown',e=>{if(e.key==='Escape'){cancelHeld();editorMode=null;confirmation=null}});
document.querySelector('#guide-close').addEventListener('click',closeGuide);
document.querySelector('#guide-settings').addEventListener('click',e=>{let panel=document.querySelector('#guide-settings-panel');panel.hidden=!panel.hidden;e.currentTarget.ariaExpanded=String(!panel.hidden)});
document.querySelector('#background-select').addEventListener('change',async e=>{save.settings.background=e.target.value;if(!img.has(e.target.value))await load(e.target.value);syncGuideSettings();persist()});
document.querySelector('#background-import-button').addEventListener('click',()=>document.querySelector('#background-import').click());
document.querySelector('#background-import').addEventListener('change',async e=>{let file=e.target.files[0];if(!file)return;let response=await fetch('/api/backgrounds',{method:'POST',headers:{'Content-Type':file.type||'application/octet-stream','X-Filename':encodeURIComponent(file.name)},body:file});if(!response.ok){alert(`Import failed: ${await response.text()}`);return}let added=await response.json();catalogue.backgrounds.push(added);await load(added.image);save.settings.background=added.image;syncGuideSettings();persist();e.target.value=''});
document.querySelector('#horizon-slider').addEventListener('input',e=>{let value=Number(e.target.value);save.settings.horizon=value/100;document.querySelector('#horizon-value').value=`${value}%`;document.querySelector('#horizon-line').style.top=`${value}%`;persist()});
document.querySelector('#row-count-slider').addEventListener('input',e=>{save.settings.row_count=Number(e.target.value);document.querySelector('#row-count-value').value=`${e.target.value} rows`;persist()});
(async()=>{catalogue=await fetch('/api/catalogue').then(r=>r.json()).catch(()=>({packs:['animals','famous_art','ui_elements'].map(id=>({id,icon:`packs/${id}/icon.png`})),minigames:['flashcards','memorycards','memoryracer'].map(id=>({id,icon:`minigames/${id}/icon.png`})),flowers:['blue','poppy','purple','rose','yellow'].map(id=>({id,image:`assets/flowers/${id}.png`})),furniture:[],backgrounds:[{id:'field',image:'assets/backgrounds/field.png'}]}));let remote=await fetch('/api/save').then(r=>r.json()).catch(()=>null),local=localStorage.getItem('knowledge-bloom-save');save=remote||(local&&JSON.parse(local))||fresh();save.settings.background??='assets/backgrounds/field.png';save.settings.horizon??=.5;save.settings.row_count??=6;catalogue.backgrounds??=[{id:'field',image:'assets/backgrounds/field.png'}];if(!save.inventory.furniture.length)save.inventory.furniture=catalogue.furniture.map(f=>({...f,status:'stored'}));let assets=['assets/info/game_info.png',...catalogue.backgrounds.map(x=>x.image),...['new_pack_button','pack_left','pack_title_frame','pack_right','guide_button','cloud_carousel_left','cloud_carousel_right','tray','edit_button','cloud_box'].map(x=>`assets/ui/${x}.png`),...catalogue.packs.map(x=>x.icon),...catalogue.minigames.map(x=>x.icon),...catalogue.flowers.map(x=>x.image),...catalogue.furniture.map(x=>x.image)];await Promise.all([...new Set(assets)].map(load));document.querySelector('#loading').remove();frame()})();
