const panel=document.querySelector('#flower-editor');
const canvas=document.querySelector('#flower-alignment-canvas'),context=canvas.getContext('2d',{willReadFrequently:true});
const select=document.querySelector('#flower-editor-select'),nameInput=document.querySelector('#flower-editor-name');
const status=document.querySelector('#flower-editor-status');
let source=null,sourceUrl='',frame=0,frameWidth=0,frameHeight=0,scale=1;
let offsets=Array.from({length:8},()=>({x:0,y:0})),drag=null;
const labels=['Seedling · watered','Sprout · watered','Growing · watered','Bloom · watered','Seedling · unwatered','Sprout · unwatered','Growing · unwatered','Bloom · unwatered'];

function imageFrom(url){return new Promise((resolve,reject)=>{let image=new Image();image.onload=()=>resolve(image);image.onerror=()=>reject(new Error('The selected image could not be opened.'));image.src=url})}
function refreshChoices(selected=''){fetch('/api/catalogue').then(r=>r.json()).then(data=>{select.replaceChildren(...data.flowers.map(f=>new Option(f.id,f.image,f.image===selected,f.image===selected)));if(!selected&&select.value)choose(select.value)})}
async function choose(url,displayName=''){
 try{source=await imageFrom(url);sourceUrl=url;frameWidth=Math.floor(source.naturalWidth/4);frameHeight=Math.floor(source.naturalHeight/2);if(!frameWidth||!frameHeight)throw new Error('Image is too small.');offsets=Array.from({length:8},()=>({x:0,y:0}));frame=0;nameInput.value=(displayName||url.split('/').pop().replace(/\.[^.]+$/,'')).replace(/[^A-Za-z0-9_-]/g,'_');status.textContent='';draw()}catch(error){status.textContent=error.message}
}
function draw(){if(!source)return;context.clearRect(0,0,canvas.width,canvas.height);scale=Math.min(1,(canvas.width-50)/frameWidth,(canvas.height-50)/frameHeight);let o=offsets[frame],x=canvas.width/2-frameWidth*scale/2+o.x,y=canvas.height-frameHeight*scale+o.y;context.imageSmoothingEnabled=false;context.drawImage(source,(frame%4)*frameWidth,Math.floor(frame/4)*frameHeight,frameWidth,frameHeight,x,y,frameWidth*scale,frameHeight*scale);document.querySelector('#flower-frame-label').textContent=labels[frame];document.querySelector('#flower-frame-count').textContent=`Frame ${frame+1} of 8`;document.querySelector('#flower-frame-previous').disabled=frame===0;document.querySelector('#flower-frame-next').disabled=frame===7}
function moveFrame(by){frame=Math.max(0,Math.min(7,frame+by));draw()}
function alphaBounds(index){let scratch=document.createElement('canvas');scratch.width=frameWidth;scratch.height=frameHeight;let c=scratch.getContext('2d',{willReadFrequently:true});c.drawImage(source,(index%4)*frameWidth,Math.floor(index/4)*frameHeight,frameWidth,frameHeight,0,0,frameWidth,frameHeight);let pixels=c.getImageData(0,0,frameWidth,frameHeight).data,minX=frameWidth,minY=frameHeight,maxX=-1,maxY=-1;for(let y=0;y<frameHeight;y++)for(let x=0;x<frameWidth;x++)if(pixels[(y*frameWidth+x)*4+3]>5){minX=Math.min(minX,x);minY=Math.min(minY,y);maxX=Math.max(maxX,x);maxY=Math.max(maxY,y)}return maxX<0?{minX:0,minY:0,maxX:0,maxY:0}:{minX,minY,maxX,maxY}}
function buildSheet(){let bounds=offsets.map((o,n)=>{let b=alphaBounds(n),dx=o.x/scale,dy=o.y/scale;return {...b,left:b.minX+dx,right:b.maxX+dx,top:b.minY+dy,bottom:b.maxY+dy}}),left=Math.floor(Math.min(...bounds.map(b=>b.left-frameWidth/2))),right=Math.ceil(Math.max(...bounds.map(b=>b.right-frameWidth/2))),top=Math.floor(Math.min(...bounds.map(b=>b.top-frameHeight))),bottom=Math.ceil(Math.max(0,...bounds.map(b=>b.bottom-frameHeight))),cellWidth=Math.max(1,right-left+1),cellHeight=Math.max(1,bottom-top+1),output=document.createElement('canvas');output.width=cellWidth*4;output.height=cellHeight*2;let c=output.getContext('2d');offsets.forEach((o,n)=>c.drawImage(source,(n%4)*frameWidth,Math.floor(n/4)*frameHeight,frameWidth,frameHeight,(n%4)*cellWidth-left-frameWidth/2+o.x/scale,Math.floor(n/4)*cellHeight-top-frameHeight+o.y/scale,frameWidth,frameHeight));return output}
function pointer(e){let r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*canvas.width/r.width,y:(e.clientY-r.top)*canvas.height/r.height}}
canvas.addEventListener('pointerdown',e=>{if(!source)return;let p=pointer(e);drag={...p,startX:offsets[frame].x,startY:offsets[frame].y};canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(!drag)return;let p=pointer(e);offsets[frame]={x:drag.startX+p.x-drag.x,y:drag.startY+p.y-drag.y};draw()});canvas.addEventListener('pointerup',()=>drag=null);canvas.addEventListener('pointercancel',()=>drag=null);
document.querySelector('#open-flower-editor').addEventListener('click',()=>{panel.hidden=false;document.querySelector('#guide').hidden=true;refreshChoices()});document.querySelector('#flower-editor-close').addEventListener('click',()=>panel.hidden=true);select.addEventListener('change',()=>choose(select.value));
document.querySelector('#flower-editor-upload').addEventListener('change',e=>{let file=e.target.files[0];if(!file)return;if(sourceUrl.startsWith('blob:'))URL.revokeObjectURL(sourceUrl);choose(URL.createObjectURL(file),file.name.replace(/\.[^.]+$/,''));e.target.value=''});
document.querySelector('#flower-frame-previous').addEventListener('click',()=>moveFrame(-1));document.querySelector('#flower-frame-next').addEventListener('click',()=>moveFrame(1));document.querySelector('#flower-frame-reset').addEventListener('click',()=>{offsets[frame]={x:0,y:0};draw()});
document.querySelector('#flower-editor-save').addEventListener('click',()=>{let name=nameInput.value.trim();if(!/^[A-Za-z0-9_-]+$/.test(name)){status.textContent='Use only letters, numbers, hyphens and underscores in the name.';return}status.textContent='Saving…';buildSheet().toBlob(async blob=>{try{let response=await fetch('/api/flowers',{method:'POST',headers:{'Content-Type':'image/png','X-Filename':encodeURIComponent(name+'.png')},body:blob});if(!response.ok)throw new Error(await response.text());let saved=await response.json();status.textContent=`Saved ${saved.image} (${saved.width} × ${saved.height}px)`;refreshChoices(saved.image)}catch(error){status.textContent=`Save failed: ${error.message}`}},'image/png')});
