const overlay=document.querySelector('#pack-editor'),start=document.querySelector('#pack-editor-start'),form=document.querySelector('#pack-editor-form'),packFields=document.querySelector('#pack-fields'),questionList=document.querySelector('#question-list'),status=document.querySelector('#pack-editor-status');
let draftId=null,model=null,mode='minimal',dirty=false;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const slug=s=>String(s).toLowerCase().trim().replace(/[^a-z0-9_-]+/g,'_').replace(/^_+|_+$/g,'').slice(0,64);
const list=v=>Array.isArray(v)?v.join('\n'):v||'';
const field=(label,path,value,type='text',level='minimal',hint='')=>`<label class="editor-field" data-level="${level}"><span>${label}</span>${type==='textarea'?`<textarea data-path="${path}" placeholder="${hint}">${esc(value)}</textarea>`:`<input data-path="${path}" type="${type}" value="${esc(value)}" placeholder="${hint}">`}</label>`;
const check=(label,path,value,level='full')=>`<label class="flag" data-level="${level}"><input data-path="${path}" type="checkbox" ${value?'checked':''}> ${label}</label>`;
function blankModel(){return {manifest:{schema_version:'1.0',pack_id:'',title:'',subtitle:'',description:'',author:'',version:'1.0.0',language:'en-GB',item_files:['items.json'],item_order:'defined',default_round_size:10,capabilities:{multiple_choice:true,typed_answer:true,categorize:false,media_only:false},reversible:false,tags:[],suggested_follow_up_packs:[],license:{name:'',url:''},credits:[]},items:[]}}
function blankItem(){return {item_id:`question_${model.items.length+1}`,question:{text:'',image:'',audio:'',video:'',category:'',credit:{creator:'',source:'',license:''}},answer:{text:'',accepted_answers:[],comparison:{case_sensitive:false,trim_whitespace:true}},distractors:[],distractor_exclusions:[],explanation:{text:'',image:'',audio:'',video:''},tags:[],important:false}}
async function createDraft(payload={}){let r=await fetch('/api/pack-drafts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!r.ok)throw Error(await r.text());let data=await r.json();draftId=data.draft_id;model=data.data;dirty=false;render()}
function open(){overlay.hidden=false;document.body.classList.add('editing-pack');start.hidden=false;form.hidden=true;status.textContent='';populatePacks()}
function close(){if(dirty&&!confirm('Discard your unsaved pack changes?'))return;overlay.hidden=true;document.body.classList.remove('editing-pack');draftId=null;model=null;dirty=false}
async function populatePacks(){let select=document.querySelector('#stored-pack-select');let data=await fetch('/api/catalogue').then(r=>r.json());select.replaceChildren(new Option('Choose a pack…',''),...data.packs.map(p=>new Option(p.title||p.id,p.id)))}
function render(){start.hidden=true;form.hidden=false;let m=model.manifest;m.capabilities??={};m.license??={};packFields.innerHTML=[field('Display name *','manifest.title',m.title),field('Pack ID *','manifest.pack_id',m.pack_id,'text','minimal','lowercase_name'),field('Short subtitle','manifest.subtitle',m.subtitle),field('Description','manifest.description',m.description,'textarea'),field('Author','manifest.author',m.author,'text','full'),field('Language','manifest.language',m.language,'text','full'),field('Version','manifest.version',m.version,'text','full'),field('Default round size','manifest.default_round_size',m.default_round_size,'number','full'),field('Tags (one per line)','manifest.tags',list(m.tags),'textarea','full'),field('Suggested follow-ups','manifest.suggested_follow_up_packs',list(m.suggested_follow_up_packs),'textarea','full'),field('License name','manifest.license.name',m.license.name,'text','extended'),field('License URL','manifest.license.url',m.license.url,'url','extended'),`<fieldset data-level="full"><legend>Key flags</legend>${check('Multiple choice','manifest.capabilities.multiple_choice',m.capabilities.multiple_choice)}${check('Typed answer','manifest.capabilities.typed_answer',m.capabilities.typed_answer)}${check('Categorize','manifest.capabilities.categorize',m.capabilities.categorize)}${check('Media-only questions','manifest.capabilities.media_only',m.capabilities.media_only)}${check('Reversible questions','manifest.reversible',m.reversible)}</fieldset>`,field('Pack credits (JSON)','manifest.credits',JSON.stringify(m.credits||[],null,2),'textarea','extended')].join('');questionList.replaceChildren(...model.items.map(questionCard));setMode(mode);status.textContent='Draft — not saved'}
function media(kind,path,value,index){return `<label class="media-upload"><span>${kind[0].toUpperCase()+kind.slice(1)}</span><input data-media-path="${path}" data-index="${index}" type="file" accept="${kind}/*"><small>${value?`Current: ${esc(value)}`:'Choose a file'}</small></label>`}
function questionCard(item,index){let q=item.question??={},a=item.answer??={},ex=item.explanation??={},credit=q.credit??={};let article=document.createElement('article');article.className='editor-card question-card';article.dataset.index=index;article.innerHTML=`<header><span class="question-number">${String(index+1).padStart(2,'0')}</span><div><h3>Question ${index+1}</h3><small>${esc(item.item_id||'Untitled')}</small></div><button class="remove-question" type="button">Remove</button></header><div class="question-fields">${field('Question *',`items.${index}.question.text`,q.text,'textarea')}${field('Answer *',`items.${index}.answer.text`,a.text)}${field('Question ID',`items.${index}.item_id`,item.item_id,'text','full')}${field('Category',`items.${index}.question.category`,q.category,'text','full')}${field('Accepted answers (one per line)',`items.${index}.answer.accepted_answers`,list(a.accepted_answers),'textarea','full')}${field('Distractors (one per line)',`items.${index}.distractors`,list(item.distractors),'textarea','full')}${field('Distractor exclusions',`items.${index}.distractor_exclusions`,list(item.distractor_exclusions),'textarea','full')}${field('Explanation',`items.${index}.explanation.text`,ex.text,'textarea','full')}</div><div class="media-row"><h4>Question media</h4>${media('image',`items.${index}.question.image`,q.image,index)}${media('audio',`items.${index}.question.audio`,q.audio,index)}${media('video',`items.${index}.question.video`,q.video,index)}</div><div class="media-row"><h4>Answer media</h4>${media('image',`items.${index}.answer.image`,a.image,index)}${media('audio',`items.${index}.answer.audio`,a.audio,index)}${media('video',`items.${index}.answer.video`,a.video,index)}</div><div class="media-row" data-level="full"><h4>Explanation media</h4>${media('image',`items.${index}.explanation.image`,ex.image,index)}${media('audio',`items.${index}.explanation.audio`,ex.audio,index)}${media('video',`items.${index}.explanation.video`,ex.video,index)}</div><div class="flags-row">${check('Important question',`items.${index}.important`,item.important)}${check('Case-sensitive answer',`items.${index}.answer.comparison.case_sensitive`,a.comparison?.case_sensitive)}${check('Trim whitespace',`items.${index}.answer.comparison.trim_whitespace`,a.comparison?.trim_whitespace)}</div><div class="attribution" data-level="extended"><h4>Question attribution</h4>${field('Creator',`items.${index}.question.credit.creator`,credit.creator,'text','extended')}${field('Source',`items.${index}.question.credit.source`,credit.source,'text','extended')}${field('License',`items.${index}.question.credit.license`,credit.license,'text','extended')}</div>`;return article}
function setPath(path,value){let parts=path.split('.'),target=model;for(let p of parts.slice(0,-1))target=target[p]??=(/^\d+$/.test(parts[parts.indexOf(p)+1])?[]:{});target[parts.at(-1)]=value}
function setMode(next){mode=next;overlay.dataset.mode=mode;document.querySelectorAll('.editor-mode button').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode))}
form.addEventListener('input',e=>{let path=e.target.dataset.path;if(!path)return;let value=e.target.type==='checkbox'?e.target.checked:e.target.value;if(/tags|suggested_follow_up_packs|accepted_answers|distractors|distractor_exclusions/.test(path))value=value.split('\n').map(x=>x.trim()).filter(Boolean);if(path==='manifest.default_round_size')value=Number(value);if(path==='manifest.credits'){try{value=JSON.parse(value)}catch{return}}setPath(path,value);dirty=true;status.textContent='Unsaved changes'});
form.addEventListener('change',async e=>{if(!e.target.dataset.mediaPath||!e.target.files[0])return;let file=e.target.files[0];status.textContent=`Uploading ${file.name}…`;let r=await fetch(`/api/pack-drafts/${draftId}/media`,{method:'POST',headers:{'X-Filename':encodeURIComponent(file.name),'X-Media-Path':e.target.dataset.mediaPath},body:file});if(!r.ok){alert(await r.text());return}let data=await r.json();setPath(e.target.dataset.mediaPath,data.path);dirty=true;render()});
form.addEventListener('click',e=>{let modeButton=e.target.closest('[data-mode]');if(modeButton)return setMode(modeButton.dataset.mode);if(e.target.id==='add-question'){model.items.push(blankItem());dirty=true;render();setTimeout(()=>questionList.lastElementChild?.scrollIntoView({behavior:'smooth'}));}if(e.target.classList.contains('remove-question')){let i=Number(e.target.closest('.question-card').dataset.index);if(confirm(`Remove question ${i+1}?`)){model.items.splice(i,1);dirty=true;render()}}});
document.querySelector('#blank-pack').addEventListener('click',()=>createDraft({data:blankModel()}).catch(e=>alert(e.message)));
document.querySelector('#load-stored-pack').addEventListener('click',()=>{let id=document.querySelector('#stored-pack-select').value;if(id)createDraft({source_id:id}).catch(e=>alert(e.message))});
document.querySelector('#pack-json-upload').addEventListener('change',async e=>{let file=e.target.files[0];if(!file)return;try{let imported=JSON.parse(await file.text()),name=prompt('JSON is valid. Name this pack:',imported.title||imported.pack?.title||file.name.replace(/\.json$/i,''));if(!name)return;await createDraft({data:imported,name})}catch(error){alert(`This is not a valid pack JSON file. ${error.message}`)}e.target.value=''});
document.querySelector('#pack-editor-save').addEventListener('click',async()=>{if(!model)return;if(!model.manifest.title.trim()||!model.manifest.pack_id.trim()||!model.items.length||model.items.some(i=>!i.question?.text?.trim()||!i.answer?.text?.trim()))return alert('Add a display name, pack ID, and at least one complete question and answer.');status.textContent='Saving…';let r=await fetch(`/api/pack-drafts/${draftId}/save`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(model)});if(!r.ok){status.textContent='Save failed';return alert(await r.text())}dirty=false;status.textContent='Saved';alert('Your learning pack was saved. It will appear in the pack list after refresh.');location.reload()});
document.querySelector('#pack-editor-close').addEventListener('click',close);addEventListener('open-pack-editor',open);
