const field=document.querySelector('#field'),fallZone=document.querySelector('#fall-zone'),basket=document.querySelector('#basket'),stack=document.querySelector('#question-stack'),status=document.querySelector('#status'),overlay=document.querySelector('#overlay');
const progressLabel=document.querySelector('#progress-label'),progressBar=document.querySelector('#progress-bar'),counts={correct:document.querySelector('#correct-count'),streak:document.querySelector('#streak'),misses:document.querySelector('#misses')};
let session=null,queue=[],records=new Map(),wave=[],basketX=.5,lastTime=0,speed=.07125,running=false,resolving=false,finished=0,streak=0,misses=0,startedAt=0,submitted=false,keys=new Set(),animationId=0,rowGap=.34,spawnY=-.18;
const catchY=.84,visibleRows=3,feedbackDelay=500;
const key=item=>`${item.pack_id}:${item.item_id}`;
const shuffle=values=>{let result=[...values];for(let i=result.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[result[i],result[j]]=[result[j],result[i]]}return result};
const element=(tag,props={},...children)=>{let node=document.createElement(tag);for(let [name,value] of Object.entries(props)){if(name==='class')node.className=value;else if(name.startsWith('on'))node.addEventListener(name.slice(2).toLowerCase(),value);else if(name.includes('-'))node.setAttribute(name,value);else node[name]=value}node.append(...children.filter(value=>value!=null));return node};
const side=item=>item.content?.question||{};
const target=item=>item.content?.answer||{};
function contentNodes(content,klass='item-text'){let nodes=[];if(content?.image)nodes.push(element('img',{src:content.image,alt:content.text||''}));if(content?.text)nodes.push(element('span',{class:klass},content.text));if(!nodes.length)nodes.push(element('span',{class:klass},'Clue'));return nodes}

function start(value){session=value;if(!Array.isArray(session.items)||session.items.length<2)return showError('Falling Answers needs at least two compatible text or image items.');records=new Map(session.items.map(item=>[key(item),{item,attempts:[],teaching_card_shown:item.interaction_type!=='introduction',attention_check_completed:false,extra_misses:0}]));queue=shuffle(session.items);let introductions=session.items.filter(item=>item.interaction_type==='introduction');if(introductions.length)showLessons(introductions);else beginRound()}
function showLessons(items){let index=0;overlay.hidden=false;const show=()=>{let item=items[index],last=index===items.length-1,record=records.get(key(item));record.teaching_card_shown=true;overlay.replaceChildren(element('div',{class:'panel'},element('span',{class:'eyebrow'},`New memory ${index+1} of ${items.length}`),element('h2',{},'See what belongs together'),element('p',{},'You will catch the clue on the left when the answer on the right reaches the front of the queue.'),element('div',{class:'teaching'},element('div',{class:'teach-side'},...contentNodes(side(item))),element('span',{},'→'),element('div',{class:'teach-side'},...contentNodes(target(item)))),element('button',{class:'primary',type:'button',onclick:()=>{if(last){overlay.hidden=true;beginRound()}else{index++;show()}}},last?'Start catching':'Next memory')))};show()}
function beginRound(){startedAt=Date.now();field.focus();renderStack();newWave();running=true;lastTime=performance.now();animationId=requestAnimationFrame(tick);update()}
function renderStack(feedback=''){stack.replaceChildren(...queue.slice(0,3).map((item,index)=>element('div',{class:`question-card ${index===0?'current':''} ${index===0?feedback:''}`},element('span',{class:'number'},String(index+1)),...contentNodes(target(item)))))}
function candidateItems(current){let wrongPool=session.items.filter(item=>key(item)!==key(current)),wrongCount=Math.random()<.5?3:4,wrong=[];while(wrong.length<wrongCount)wrong.push(...shuffle(wrongPool).slice(0,wrongCount-wrong.length));return shuffle([current,...wrong])}
function createRow(current,y){let candidates=candidateItems(current),count=candidates.length,width=1/count,entries=candidates.map((item,index)=>{let variance=(Math.random()-.5)*Math.min(.045,width*.18),x=(index+.5)*width+variance,node=element('div',{class:'falling-item',role:'img','aria-label':side(item).text||'Image clue'},...contentNodes(side(item)));fallZone.append(node);return {item,x,node}}).sort((a,b)=>a.x-b.x);return {entries,y}}
function newWave(){wave=[];queue.slice(0,visibleRows).forEach(current=>wave.push(createRow(current,0)));let tallest=Math.max(...wave.flatMap(row=>row.entries.map(entry=>entry.node.offsetHeight)),0);spawnY=-(tallest/2+8)/field.clientHeight;rowGap=(catchY-spawnY)/visibleRows;wave.forEach((row,index)=>row.y=spawnY-index*rowGap);positionWave()}
function positionWave(){for(let row of wave)for(let entry of row.entries)entry.node.style.transform=`translate(-50%, -50%) translate(${entry.x*field.clientWidth}px, ${row.y*field.clientHeight}px)`}
function tick(time){if(!running)return;let delta=Math.min(.04,(time-lastTime)/1000);lastTime=time;let direction=(keys.has('arrowleft')||keys.has('a')?-1:0)+(keys.has('arrowright')||keys.has('d')?1:0);if(direction)moveBasket(basketX+direction*delta*1.35);if(!resolving){for(let row of wave)row.y+=delta*speed;positionWave();if(wave[0]?.y>=catchY)resolveWave()}animationId=requestAnimationFrame(tick)}
function moveBasket(value){basketX=Math.max(.055,Math.min(.945,value));basket.style.left=`${basketX*100}%`}
function resolveWave(){if(resolving)return;resolving=true;let basketWidth=basket.getBoundingClientRect().width/field.clientWidth,caught=[...wave[0].entries].sort((a,b)=>Math.abs(a.x-basketX)-Math.abs(b.x-basketX))[0],distance=Math.abs(caught.x-basketX),within=distance<=(basketWidth/2+.025),correct=within&&key(caught.item)===key(queue[0]);if(!within)correct=false;handleAnswer(correct,caught)}
function handleAnswer(correct,caught){let current=queue[0],record=records.get(key(current));if(correct){record.attempts.push({correct:true});record.attention_check_completed=current.interaction_type==='introduction';finished++;streak++;caught.node.classList.add('correct-flash');status.textContent=streak>1?`Wonderful — ${streak} catches in a row!`:'Correct catch! The next answer is moving up.';renderStack('caught-right');queue.shift()}else{if(record.attempts.filter(attempt=>!attempt.correct).length<2)record.attempts.push({correct:false});else record.extra_misses++;misses++;streak=0;if(caught)caught.node.classList.add('wrong-flash');status.textContent='That clue does not match. It will come around again.';renderStack('caught-wrong');queue.push(queue.shift())}update();setTimeout(()=>advanceWave(),feedbackDelay)}
function advanceWave(){let resolved=wave.shift();resolved.entries.forEach(entry=>entry.node.remove());if(!queue.length){resolving=false;finish();return}if(wave.length<Math.min(visibleRows,queue.length))wave.push(createRow(queue[wave.length],spawnY));renderStack();positionWave();lastTime=performance.now();resolving=false}
function update(){let total=session?.items?.length||0;counts.correct.textContent=finished;counts.streak.textContent=streak;counts.misses.textContent=misses;progressLabel.textContent=`${finished} of ${total} answers safely caught`;progressBar.style.width=`${total?finished/total*100:0}%`;speed=Math.min(.1275,.07125+finished*.003)}
function finish(){running=false;cancelAnimationFrame(animationId);let results=[...records.values()].map(record=>({pack_id:record.item.pack_id,item_id:record.item.item_id,interaction_type:record.item.interaction_type,attempts:record.attempts,first_attempt_correct:record.attempts[0]?.correct===true,finished_correctly:true,deferred:false,...(record.item.interaction_type==='introduction'?{introduction:{teaching_card_shown:record.teaching_card_shown,attention_check_completed:record.attention_check_completed}}:{})}));let summary={items_presented:results.length,new_items_introduced:results.filter(result=>result.interaction_type==='introduction'&&result.finished_correctly).length,first_attempt_correct:results.filter(result=>result.first_attempt_correct).length,items_finished_correctly:results.length,items_deferred:0},result={result_schema_version:'1.0',session_id:session.session_id,game_id:session.game_id,user_id:session.user_id,round_completed:true,ended_at:new Date().toISOString(),summary,results,game_metrics:{caught:finished,misses,extra_practice_misses:[...records.values()].reduce((sum,record)=>sum+record.extra_misses,0),best_streak:streak,time_seconds:Math.round((Date.now()-startedAt)/1000)}};submitted=true;parent.postMessage({type:'knowledge-bloom:result',result},location.origin);showSummary(summary,false)}
function stat(value,label){return element('div',{},element('strong',{},String(value)),label)}
function rewardDetails(rewards){let box=element('div',{class:'reward-summary'});for(let award of rewards?.awards||[])box.append(element('p',{},`${award.reason}: +${award.amount} Garden Points`));return box}
function showSummary(summary,accepted,rewards){overlay.hidden=false;overlay.replaceChildren(element('div',{class:'panel'},element('span',{class:'eyebrow'},accepted?'Saved to your garden':'Round complete'),element('h2',{},'Every answer is safely gathered!'),element('div',{class:'summary-grid'},stat(summary.items_presented,'Answers caught'),stat(summary.first_attempt_correct,'First-time correct'),stat(misses,'Misses'),stat(Math.round((Date.now()-startedAt)/1000)+'s','Time')),element('p',{},accepted?'Your learning results have been applied and the garden is ready for you.':'Saving your learning results…'),accepted?rewardDetails(rewards):null,element('button',{class:'primary',type:'button',disabled:!accepted,onclick:()=>parent.postMessage({type:'knowledge-bloom:close'},location.origin)},'Return to the garden')))}
function showError(message){running=false;overlay.hidden=false;overlay.replaceChildren(element('div',{class:'panel'},element('h2',{},'The meadow is not ready'),element('p',{},message),element('button',{class:'primary',type:'button',onclick:()=>parent.postMessage({type:'knowledge-bloom:close'},location.origin)},'Return to the garden')))}

addEventListener('keydown',event=>{let value=event.key.toLowerCase();if(['arrowleft','arrowright','a','d'].includes(value)){event.preventDefault();keys.add(value)}});addEventListener('keyup',event=>keys.delete(event.key.toLowerCase()));
field.addEventListener('pointermove',event=>{let rect=field.getBoundingClientRect();moveBasket((event.clientX-rect.left)/rect.width)});field.addEventListener('pointerdown',event=>{field.setPointerCapture(event.pointerId);let rect=field.getBoundingClientRect();moveBasket((event.clientX-rect.left)/rect.width)});
addEventListener('resize',positionWave);addEventListener('message',event=>{if(event.origin!==location.origin||event.source!==parent)return;if(event.data?.type==='knowledge-bloom:session'&&!session)start(event.data.session);if(event.data?.type==='knowledge-bloom:result-ack'&&submitted){if(event.data.accepted)showSummary({items_presented:session.items.length,first_attempt_correct:[...records.values()].filter(record=>record.attempts[0]?.correct).length},true,event.data.consequences?.garden_points);else showError('Your results could not be saved. Please return to the garden and try again.')}});
document.querySelector('#leave').addEventListener('click',()=>{if(confirm('Leave this round? Unfinished answers will not be saved.'))parent.postMessage({type:'knowledge-bloom:close',round_completed:false},location.origin)});
parent.postMessage({type:'knowledge-bloom:ready'},location.origin);
