const card=document.querySelector('#card'),progressLabel=document.querySelector('#progress-label'),progressBar=document.querySelector('#progress-bar');
let session=null,queue=[],records=new Map(),uniqueFinished=0,current=null,mode='multiple_choice',submitted=false,feedbackAdvance=null,feedbackActivation=0;
const shuffle=values=>{let a=[...values];for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
const key=item=>`${item.pack_id}:${item.item_id}`;
const normalize=value=>String(value??'').normalize('NFKC').trim().toLocaleLowerCase().replace(/[.!?,;:]+$/g,'');
const element=(tag,props={},...children)=>{let node=document.createElement(tag);for(let [name,value] of Object.entries(props)){if(name==='class')node.className=value;else if(name.startsWith('on'))node.addEventListener(name.slice(2).toLowerCase(),value);else if(name.includes('-'))node.setAttribute(name,value);else node[name]=value}node.append(...children.filter(x=>x!=null));return node};

function media(content){let nodes=[];if(content?.image)nodes.push(element('img',{class:'question-media',src:content.image,alt:''}));if(content?.audio)nodes.push(element('audio',{class:'media-player',src:content.audio,controls:true,preload:'metadata'}));if(content?.video)nodes.push(element('video',{class:'media-player',src:content.video,controls:true,preload:'metadata'}));return nodes}
function start(value){session=value;mode=session.settings?.answer_mode||'multiple_choice';records=new Map(session.items.map(item=>[key(item),{item,attempts:[],teaching_card_shown:false,attention_check_completed:false,deferred:false,finished:false}]));queue=session.items.filter(i=>i.interaction_type!=='introduction').map(item=>({kind:'question',item}));for(let item of session.items.filter(i=>i.interaction_type==='introduction')){let position=Math.min(queue.length,Math.floor(Math.random()*(queue.length+1))),gap=1+Math.floor(Math.random()*3);queue.splice(position,0,{kind:'teach',item});queue.splice(Math.min(queue.length,position+1+gap),0,{kind:'question',item})}next()}
function updateProgress(){let total=session?.items.length||0;progressLabel.textContent=`${uniqueFinished} of ${total} memories complete`;progressBar.style.width=`${total?uniqueFinished/total*100:0}%`}
function next(){feedbackAdvance=null;feedbackActivation++;updateProgress();if(!queue.length)return finish();current=queue.shift();current.kind==='teach'?showTeaching(current.item):showQuestion(current.item)}
function showTeaching(item,retry=false){let record=records.get(key(item));record.teaching_card_shown=true;let content=item.content,answer=content.answer||{};card.replaceChildren(element('span',{class:'badge'},retry?'A helpful reminder':'New memory'),element('h2',{},retry?'Take another look':'Meet something new'),...media(content.question),element('p',{class:'answer'},answer.text),answer.image?media(answer)[0]:null,content.explanation?.text?element('p',{class:'explanation'},content.explanation.text):null,element('button',{class:'primary',type:'button',onclick:next},retry?'Try again soon':'Continue'))}
function showQuestion(item){let content=item.content,record=records.get(key(item)),attempt=record.attempts.length+1;let title=content.question?.text||'What is the answer?',heading=element('h2',{},title),badge=element('span',{class:'badge'},item.interaction_type==='introduction'?'Memory check':attempt>1?`Retry ${attempt}`:item.interaction_type==='valid_review'?'Review':'Practice'),body=[badge,heading,...media(content.question)];if(mode==='typed_answer')body.push(typedControls(item));else body.push(choiceControls(item));card.replaceChildren(...body)}
function choiceControls(item){let answer=item.content.answer.text,options=shuffle([answer,...(item.distractors||[])]).filter((x,n,a)=>a.findIndex(y=>normalize(y)===normalize(x))===n).slice(0,4),wrap=element('div',{class:'choices'});for(let option of options)wrap.append(element('button',{class:'choice',type:'button',onclick:()=>answerItem(item,normalize(option)===normalize(answer))},option));let switcher=element('button',{class:'mode-switch',type:'button',onclick:()=>{mode='typed_answer';showQuestion(item)}},'Type my answer instead');return element('div',{},wrap,switcher)}
function typedControls(item){let input=element('input',{type:'text',autocomplete:'off',placeholder:'Type your answer…','aria-label':'Your answer'}),form=element('form',{class:'typed-form',onsubmit:event=>{event.preventDefault();if(!input.value.trim())return;let accepted=[item.content.answer.text,...(item.content.answer.accepted_answers||[])].map(normalize);answerItem(item,accepted.includes(normalize(input.value))) }},input,element('button',{class:'primary',type:'submit'},'Check answer')),switcher=element('button',{class:'mode-switch',type:'button',onclick:()=>{mode='multiple_choice';showQuestion(item)}},'Use answer choices instead');setTimeout(()=>input.focus());return element('div',{},form,switcher)}
function answerItem(item,correct){let record=records.get(key(item));record.attempts.push({correct});if(correct){record.finished=true;if(item.interaction_type==='introduction')record.attention_check_completed=true;uniqueFinished++;return feedback(item,true,false)}let failures=record.attempts.filter(a=>!a.correct).length;if(failures>=3){record.deferred=true;record.finished=true;uniqueFinished++;return feedback(item,false,true)}feedback(item,false,false)}
function feedback(item,correct,deferred){let answer=item.content.answer.text,explanation=item.content.explanation?.text,heading=correct?'That’s right!':deferred?'Let’s practise this again soon':'Not quite — here is the answer',activation=++feedbackActivation,advanced=false,advance=()=>{if(advanced)return;advanced=true;feedbackAdvance=null;continueAfter(item,correct,deferred)},parts=[element('span',{class:'badge'},correct?'Correct':deferred?'Extra practice':'Keep growing'),element('h2',{class:`feedback ${correct?'correct':'wrong'}`},heading),...media(item.content.question),element('p',{class:'answer'},answer)];if(!correct&&explanation)parts.push(element('p',{class:'explanation'},explanation));parts.push(element('button',{class:'primary',type:'button',onclick:advance},deferred?'Continue':'Next card'));card.replaceChildren(...parts);setTimeout(()=>{if(feedbackActivation===activation&&!advanced)feedbackAdvance=advance})}
function continueAfter(item,correct,deferred){if(!correct&&!deferred){let record=records.get(key(item)),failures=record.attempts.filter(a=>!a.correct).length;if(failures===2)queue.push({kind:'teach',item,retry:true});queue.push({kind:'question',item})}next()}
function finish(){let results=[...records.values()].map(record=>({pack_id:record.item.pack_id,item_id:record.item.item_id,interaction_type:record.item.interaction_type,attempts:record.attempts,first_attempt_correct:record.attempts[0]?.correct===true,finished_correctly:record.attempts.at(-1)?.correct===true,deferred:record.deferred,introduction:{teaching_card_shown:record.teaching_card_shown,attention_check_completed:record.attention_check_completed}})),summary={items_presented:results.length,new_items_introduced:results.filter(r=>r.interaction_type==='introduction'&&r.finished_correctly).length,first_attempt_correct:results.filter(r=>r.first_attempt_correct).length,items_finished_correctly:results.filter(r=>r.finished_correctly).length,items_deferred:results.filter(r=>r.deferred).length},result={result_schema_version:'1.0',session_id:session.session_id,game_id:session.game_id,user_id:session.user_id,round_completed:true,ended_at:new Date().toISOString(),summary,results};submitted=true;parent.postMessage({type:'knowledge-bloom:result',result},location.origin);showSummary(summary,false)}
function rewardDetails(rewards){let box=element('div',{class:'reward-summary'});for(let award of rewards?.awards||[])box.append(element('p',{},`${award.reason}: +${award.amount} Garden Points`));return box}
function showSummary(summary,accepted,rewards){card.replaceChildren(element('span',{class:'badge'},accepted?'Saved to your garden':'Round complete'),element('h2',{},'Round Complete'),element('div',{class:'summary-grid'},stat(summary.first_attempt_correct,`of ${summary.items_presented} first-time correct`),stat(summary.items_finished_correctly,'finished correctly'),stat(summary.new_items_introduced,'new memories introduced'),stat(summary.items_deferred,'need extra practice')),element('p',{class:'explanation'},accepted?'Your learning progress and memory plants have been updated.':'Saving your learning results…'),accepted?rewardDetails(rewards):null,element('button',{class:'primary',type:'button',disabled:!accepted,onclick:()=>parent.postMessage({type:'knowledge-bloom:close'},location.origin)},'Return to the garden'))}
function stat(value,label){return element('div',{},element('strong',{},String(value)),label)}
addEventListener('message',event=>{if(event.origin!==location.origin||event.source!==parent)return;if(event.data?.type==='knowledge-bloom:session'&&!session)start(event.data.session);if(event.data?.type==='knowledge-bloom:result-ack'&&submitted){if(event.data.accepted)showSummary({items_presented:session.items.length,new_items_introduced:[...records.values()].filter(r=>r.item.interaction_type==='introduction'&&r.attempts.at(-1)?.correct).length,first_attempt_correct:[...records.values()].filter(r=>r.attempts[0]?.correct).length,items_finished_correctly:[...records.values()].filter(r=>r.attempts.at(-1)?.correct).length,items_deferred:[...records.values()].filter(r=>r.deferred).length},true,event.data.consequences?.garden_points);else card.replaceChildren(element('h2',{class:'error'},'We could not save this round'),element('p',{class:'explanation'},'Your results were not applied. Please return to the garden and try again.'),element('button',{class:'primary',onclick:()=>parent.postMessage({type:'knowledge-bloom:close'},location.origin)},'Return to the garden'))}});
document.querySelector('#leave').addEventListener('click',()=>{if(confirm('Leave this round? Your unfinished results will not be applied.'))parent.postMessage({type:'knowledge-bloom:close',round_completed:false},location.origin)});
document.addEventListener('click',event=>{if(feedbackAdvance&&!event.target.closest('#leave'))feedbackAdvance()});
parent.postMessage({type:'knowledge-bloom:ready'},location.origin);
