const grid=document.querySelector('#answer-grid'),stack=document.querySelector('#question-stack'),status=document.querySelector('#status'),overlay=document.querySelector('#overlay');
const progressLabel=document.querySelector('#progress-label'),progressBar=document.querySelector('#progress-bar'),queueLabel=document.querySelector('#queue-label'),playerCar=document.querySelector('#player-car'),rivalCar=document.querySelector('#rival-car');
const counts={correct:document.querySelector('#correct-count'),misses:document.querySelector('#misses'),timer:document.querySelector('#timer')};
let session=null,queue=[],records=new Map(),finished=0,misses=0,startedAt=0,rivalProgress=0,rivalStepMs=4000,running=false,resolving=false,submitted=false,animationId=0,lastFrame=0,bestStreak=0,streak=0;
const key=item=>`${item.pack_id}:${item.item_id}`;
const shuffle=values=>{let result=[...values];for(let i=result.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[result[i],result[j]]=[result[j],result[i]]}return result};
const element=(tag,props={},...children)=>{let node=document.createElement(tag);for(let [name,value] of Object.entries(props)){if(name==='class')node.className=value;else if(name.startsWith('on'))node.addEventListener(name.slice(2).toLowerCase(),value);else if(name.includes('-'))node.setAttribute(name,value);else node[name]=value}node.append(...children.filter(value=>value!=null));return node};
const question=item=>item.content?.question||{};
const answer=item=>item.content?.answer||{};
function contentNodes(content,klass='item-text'){let nodes=[];if(content?.image)nodes.push(element('img',{src:content.image,alt:content.text||''}));if(content?.text)nodes.push(element('span',{class:klass},content.text));if(!nodes.length)nodes.push(element('span',{class:klass},'Clue'));return nodes}

function start(value){session=value;if(!Array.isArray(session.items)||session.items.length<2)return showError('Memory Racer needs at least two compatible text or image items.');records=new Map(session.items.map(item=>[key(item),{item,attempts:[],teaching_card_shown:item.interaction_type!=='introduction',attention_check_completed:false,extra_misses:0}]));queue=shuffle(session.items);let introductions=session.items.filter(item=>item.interaction_type==='introduction');if(introductions.length)showLessons(introductions);else beginRound()}
function showLessons(items){let index=0;overlay.hidden=false;const show=()=>{let item=items[index],last=index===items.length-1,record=records.get(key(item));record.teaching_card_shown=true;overlay.replaceChildren(element('div',{class:'panel'},element('span',{class:'eyebrow'},`New memory ${index+1} of ${items.length}`),element('h2',{},'Learn this racing pair'),element('p',{},'During the race, choose the answer card that matches each question.'),element('div',{class:'teaching'},element('div',{class:'teach-side'},...contentNodes(question(item))),element('span',{},'→'),element('div',{class:'teach-side'},...contentNodes(answer(item)))),element('button',{class:'primary',type:'button',onclick:()=>{if(last){overlay.hidden=true;beginRound()}else{index++;show()}}},last?'Start the race':'Next memory')))};show()}
function beginRound(){startedAt=Date.now();rivalStepMs=3000+Math.random()*2000;renderAnswers();renderStack();update();running=true;lastFrame=performance.now();animationId=requestAnimationFrame(tick)}
function renderAnswers(){let count=queue.length,columns=Math.ceil(Math.sqrt(count*1.35));grid.style.setProperty('--columns',Math.max(2,Math.min(6,columns)));let cards=shuffle(queue).map(item=>element('button',{class:'answer-card',type:'button','data-key':key(item),'aria-label':`Answer: ${answer(item).text||'image'}`,onclick:event=>choose(item,event.currentTarget)},...contentNodes(answer(item))));grid.replaceChildren(...cards)}
function renderStack(feedback=''){let visible=queue.slice(0,3);queueLabel.textContent=`${Math.min(3,queue.length)} in view · ${queue.length} left`;stack.replaceChildren(...visible.map((item,depth)=>element('div',{class:`question-card ${depth===0?feedback:''}`,style:`--depth:${depth}`},element('span',{class:'number'},String(depth+1)),...contentNodes(question(item)))))}
function choose(item,card){if(!running||resolving)return;let current=queue[0],record=records.get(key(current));if(key(item)!==key(current)){misses++;streak=0;if(record.attempts.filter(attempt=>!attempt.correct).length<2)record.attempts.push({correct:false});else record.extra_misses++;rivalProgress=Math.min(1,rivalProgress+0.35/session.items.length);card.classList.remove('wrong');void card.offsetWidth;card.classList.add('wrong');renderStack('wrong');status.textContent='Not that one — the rival gets a little boost!';updateCars();update();setTimeout(()=>{card.classList.remove('wrong');renderStack()},430);return}resolving=true;record.attempts.push({correct:true});record.attention_check_completed=current.interaction_type==='introduction';finished++;streak++;bestStreak=Math.max(bestStreak,streak);card.classList.add('correct');renderStack('correct');status.textContent=queue.length===1?'Finish line!':'Correct — accelerate to the next question!';update();setTimeout(()=>{queue.shift();if(!queue.length){finish();return}renderAnswers();renderStack();resolving=false},280)}
function tick(time){if(!running)return;let delta=Math.min(50,time-lastFrame);lastFrame=time;rivalProgress=Math.min(1,rivalProgress+delta/(rivalStepMs*session.items.length));updateCars();counts.timer.textContent=formatTime(Date.now()-startedAt);animationId=requestAnimationFrame(tick)}
function updateCars(){let playerProgress=finished/session.items.length,travel=94;playerCar.style.left=`calc(${playerProgress*travel}% - ${playerProgress*45}px)`;rivalCar.style.left=`calc(${rivalProgress*travel}% - ${rivalProgress*45}px)`}
function update(){let total=session?.items?.length||0;counts.correct.textContent=finished;counts.misses.textContent=misses;progressLabel.textContent=`${finished} of ${total} answers matched`;progressBar.style.width=`${total?finished/total*100:0}%`;updateCars()}
function formatTime(ms){let seconds=Math.floor(ms/1000);return `${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}`}
function finish(){running=false;cancelAnimationFrame(animationId);let elapsed=Date.now()-startedAt,playerWon=rivalProgress<1;let results=[...records.values()].map(record=>({pack_id:record.item.pack_id,item_id:record.item.item_id,interaction_type:record.item.interaction_type,attempts:record.attempts,first_attempt_correct:record.attempts[0]?.correct===true,finished_correctly:true,deferred:false,...(record.item.interaction_type==='introduction'?{introduction:{teaching_card_shown:record.teaching_card_shown,attention_check_completed:record.attention_check_completed}}:{})}));let summary={items_presented:results.length,new_items_introduced:results.filter(result=>result.interaction_type==='introduction'&&result.finished_correctly).length,first_attempt_correct:results.filter(result=>result.first_attempt_correct).length,items_finished_correctly:results.length,items_deferred:0},result={result_schema_version:'1.0',session_id:session.session_id,game_id:session.game_id,user_id:session.user_id,round_completed:true,ended_at:new Date().toISOString(),summary,results,game_metrics:{correct:finished,misses,extra_practice_misses:[...records.values()].reduce((sum,record)=>sum+record.extra_misses,0),best_streak:bestStreak,time_seconds:Math.round(elapsed/1000),race_won:playerWon}};submitted=true;parent.postMessage({type:'knowledge-bloom:result',result},location.origin);showSummary(summary,false,null,elapsed,playerWon)}
function stat(value,label){return element('div',{},element('strong',{},String(value)),label)}
function rewardDetails(rewards){let box=element('div',{class:'reward-summary'});for(let award of rewards?.awards||[])box.append(element('p',{},`${award.reason}: +${award.amount} Garden Points`));return box}
function showSummary(summary,accepted,rewards,elapsed=Date.now()-startedAt,playerWon=rivalProgress<1){overlay.hidden=false;overlay.replaceChildren(element('div',{class:'panel'},element('span',{class:'eyebrow'},accepted?'Saved to your garden':'Round complete'),element('h2',{},playerWon?'You won the Memory Race!':'You finished the Memory Race!'),element('p',{},playerWon?'Quick thinking put your car across the line first.':'The rival was speedy, but every answer made it home.'),element('div',{class:'summary-grid'},stat(summary.items_presented,'Answers matched'),stat(summary.first_attempt_correct,'First-time correct'),stat(misses,'Misses'),stat(formatTime(elapsed),'Time')),element('p',{},accepted?'Your learning results have been applied and the garden is ready for you.':'Saving your learning results…'),accepted?rewardDetails(rewards):null,element('button',{class:'primary',type:'button',disabled:!accepted,onclick:()=>parent.postMessage({type:'knowledge-bloom:close'},location.origin)},'Return to the garden')))}
function showError(message){running=false;cancelAnimationFrame(animationId);overlay.hidden=false;overlay.replaceChildren(element('div',{class:'panel'},element('h2',{},'The race is not ready'),element('p',{},message),element('button',{class:'primary',type:'button',onclick:()=>parent.postMessage({type:'knowledge-bloom:close'},location.origin)},'Return to the garden')))}

addEventListener('message',event=>{if(event.origin!==location.origin||event.source!==parent)return;if(event.data?.type==='knowledge-bloom:session'&&!session)start(event.data.session);if(event.data?.type==='knowledge-bloom:result-ack'&&submitted){if(event.data.accepted)showSummary({items_presented:session.items.length,first_attempt_correct:[...records.values()].filter(record=>record.attempts[0]?.correct).length},true,event.data.consequences?.garden_points);else showError('Your results could not be saved. Please return to the garden and try again.')}});
document.querySelector('#leave').addEventListener('click',()=>{if(confirm('Leave this round? Unfinished answers will not be saved.'))parent.postMessage({type:'knowledge-bloom:close',round_completed:false},location.origin)});
parent.postMessage({type:'knowledge-bloom:ready'},location.origin);
